### ISSUE TITLE
crash with no other mods

### ISSUE THREAD

**Issue by Axodique** [Johni0702/BetterPortals#102]
The game crashed whilst exception initializing level
Error: java.lang.IllegalArgumentException: ChunkNibbleArrays should be 2048 bytes not: 0

**Comment by Johni0702** [comment]
Context? Log?

**Comment by Axodique** [comment]
Well i downloaded the mod and forgelin at the latest version and i crashed

log:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.3.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 7/10/19 3:50 PM
Description: Exception initializing level

java.lang.IllegalArgumentException: ChunkNibbleArrays should be 2048 bytes not: 0
	at net.minecraft.world.chunk.NibbleArray.<init>(SourceFile:16)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75823_a(AnvilChunkLoader.java:449)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.checkedReadChunkFromNBT__Async(AnvilChunkLoader.java:128)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:92)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.run(ChunkIOProvider.java:70)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:92)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.World.func_175726_f(World.java:305)
	at net.minecraft.world.World.func_180495_p(World.java:911)
	at net.minecraft.world.World.func_175623_d(World.java:230)
	at net.minecraft.world.World.func_184141_c(World.java:210)
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:76)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:944)
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:866)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:123)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.chunk.NibbleArray.<init>(SourceFile:16)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75823_a(AnvilChunkLoader.java:449)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.checkedReadChunkFromNBT__Async(AnvilChunkLoader.java:128)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:92)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.run(ChunkIOProvider.java:70)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:92)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.World.func_175726_f(World.java:305)
	at net.minecraft.world.World.func_180495_p(World.java:911)
	at net.minecraft.world.World.func_175623_d(World.java:230)
	at net.minecraft.world.World.func_184141_c(World.java:210)
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:76)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:944)

-- Affected level --
Details:
	Level name: New World
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 0 Drop: 0
	Level seed: 3389472193280022946
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:866)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:123)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 401171536 bytes (382 MB) / 637534208 bytes (608 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2796 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID            | Version      | Source                        | Signature                                |
	|:------ |:------------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft     | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp           | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML           | 8.0.99.99    | forge-1.12.2-14.23.5.2796.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge         | 14.23.5.2796 | forge-1.12.2-14.23.5.2796.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forgelin      | 1.8.3        | Forgelin-1.8.3.jar            | None                                     |
	| LCHIJA | betterportals | 0.1.6        | betterportals-0.1.6.jar       | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.3.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Johni0702** [comment]
That looks more like a corrupted world than anything to do with BP. Are you sure it's related to BP?

**Comment by Axodique** [comment]
I think because i just generated the world with no other mods

**Comment by Axodique** [comment]
it crashed and then i tried getting in the world again and it crashed and i took the log from that

**Comment by Johni0702** [comment]
Does it load fine with BP?

**Comment by Axodique** [comment]
I generated the world with bo and never joined without bp

**Comment by Johni0702** [comment]
That's why I'm asking if it is even related to BP. The crash itself just looks like an issue with forge or vanilla.

**Comment by Axodique** [comment]
I'll try joining without

**Comment by Axodique** [comment]
It works without bp

**Comment by Johni0702** [comment]
Please upload your world file somewhere, so I can try to reproduce it on my machine.

**Comment by Axodique** [comment]
https://mega.nz/#F!2M4UwKKR!4D6462uOsykAtOmirDhEUQ

**Comment by Axodique** [comment]
i'll try downloading a new version of 1.12.2 forge

**Comment by Axodique** [comment]
My issue is resolved after i updated forge. Thanks for your help!
