### ISSUE TITLE
Issue with New Tardis mod

### ISSUE THREAD

**Issue by diamondstars** [Johni0702/BetterPortals#113]
When going in and out of the tardis in the new tardis mod the game crashes https://paste.dimdev.org/ejisuqoxok.mccrash

**Comment by Johni0702** [comment]
Cannot reproduce, instead I'm getting:
<details>

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.2.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 7/13/19 11:44 AM
Description: Ticking block entity

kotlin.TypeCastException: null cannot be cast to non-null type net.minecraftforge.common.capabilities.CapabilityDispatcher
	at de.johni0702.minecraft.betterportals.common.ExtensionsKt.getForgeCapabilities(Extensions.kt:269)
	at de.johni0702.minecraft.betterportals.server.DimensionTransitionHandler$transferPlayerToDimension$view$1.invoke(DimensionTransitionHandler.kt:25)
	at de.johni0702.minecraft.betterportals.server.DimensionTransitionHandler$transferPlayerToDimension$view$1.invoke(DimensionTransitionHandler.kt:13)
	at de.johni0702.minecraft.betterportals.server.view.ServerViewManagerImpl.createView(ServerViewManagerImpl.kt:75)
	at de.johni0702.minecraft.betterportals.server.DimensionTransitionHandler.transferPlayerToDimension(DimensionTransitionHandler.kt:23)
	at net.minecraft.server.management.PlayerList.handler$betterPortalPlayerToDimension$zzb000(PlayerList.java:1307)
	at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java)
	at net.tardis.mod.common.tileentity.TileEntityTardis.enterTARDIS(TileEntityTardis.java:1073)
	at net.tardis.mod.common.tileentity.TileEntityDoor.handleEnter(TileEntityDoor.java:282)
	at net.tardis.mod.common.tileentity.TileEntityDoor.func_73660_a(TileEntityDoor.java:172)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at de.johni0702.minecraft.betterportals.common.ExtensionsKt.getForgeCapabilities(Extensions.kt:269)
	at de.johni0702.minecraft.betterportals.server.DimensionTransitionHandler$transferPlayerToDimension$view$1.invoke(DimensionTransitionHandler.kt:25)
	at de.johni0702.minecraft.betterportals.server.DimensionTransitionHandler$transferPlayerToDimension$view$1.invoke(DimensionTransitionHandler.kt:13)
	at de.johni0702.minecraft.betterportals.server.view.ServerViewManagerImpl.createView(ServerViewManagerImpl.kt:75)
	at de.johni0702.minecraft.betterportals.server.DimensionTransitionHandler.transferPlayerToDimension(DimensionTransitionHandler.kt:23)
	at net.minecraft.server.management.PlayerList.handler$betterPortalPlayerToDimension$zzb000(PlayerList.java:1307)
	at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java)
	at net.tardis.mod.common.tileentity.TileEntityTardis.enterTARDIS(TileEntityTardis.java:1073)
	at net.tardis.mod.common.tileentity.TileEntityDoor.handleEnter(TileEntityDoor.java:282)
	at net.tardis.mod.common.tileentity.TileEntityDoor.func_73660_a(TileEntityDoor.java:172)

-- Block entity being ticked --
Details:
	Name: tardis:tileentitydoortt // net.tardis.mod.client.models.exteriors.TileEntityDoorTT
	Block type: ID #338 (tile.tardis.tardis_top_tt // net.tardis.mod.common.blocks.BlockTardisTop // tardis:tardis_top_tt)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (1066,5,-1137), Chunk: (at 10,0,15 in 66,-72; contains blocks 1056,0,-1152 to 1071,255,-1137), Region: (2,-3; contains chunks 64,-96 to 95,-65, blocks 1024,0,-1536 to 1535,255,-1025)
	Actual block type: ID #338 (tile.tardis.tardis_top_tt // net.tardis.mod.common.blocks.BlockTardisTop // tardis:tardis_top_tt)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['Johni0702'/63, l='New World', x=1066.26, y=4.00, z=-1137.34]]
	Chunk stats: ServerChunkCache: 529 Drop: 0
	Level seed: -9184042067213474476
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (1066,4,-1138), Chunk: (at 10,0,14 in 66,-72; contains blocks 1056,0,-1152 to 1071,255,-1137), Region: (2,-3; contains chunks 64,-96 to 95,-65, blocks 1024,0,-1536 to 1535,255,-1025)
	Level time: 1704 game time, 1704 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 37087 (now: false), thunder time: 175493 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.14.67-1.pvops.qubes.x86_64
	Java Version: 1.8.0_212, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 552973928 bytes (527 MB) / 1040711680 bytes (992 MB) up to 1219493888 bytes (1163 MB)
	JVM Flags: 2 total; -Xms512m -Xmx1308m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID            | Version      | Source                                  | Signature                                |
	|:------ |:------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft     | 1.12.2       | minecraft.jar                           | None                                     |
	| LCHIJA | mcp           | 9.42         | minecraft.jar                           | None                                     |
	| LCHIJA | FML           | 8.0.99.99    | forge-1.12.2-14.23.5.2838-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge         | 14.23.5.2838 | forge-1.12.2-14.23.5.2838-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forgelin      | 1.8.2        | Forgelin-1.8.2.jar                      | None                                     |
	| LCHIJA | betterportals | 0.1.6        | betterportals-0.1.6.jar                 | None                                     |
	| LCHIJA | tardis        | 0.1.0E       | tardis-0.1.0E.jar                       | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.2.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Johni0702'/63, l='New World', x=1066.26, y=4.00, z=-1137.34]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

```
</details>
