### ISSUE TITLE
Death in nether freezes game

### ISSUE THREAD

**Issue by VuDJuBuh** [Johni0702/BetterPortals#232]
Easy to read mods list.
[Mods.txt](https://github.com/Johni0702/BetterPortals/files/3486002/Mods.txt)

2 logs made around the same time so I thought I'd include both, hope they help.
[2019-08-08-3.log.gz](https://github.com/Johni0702/BetterPortals/files/3486004/2019-08-08-3.log.gz)
[debug-1.log.gz](https://github.com/Johni0702/BetterPortals/files/3486005/debug-1.log.gz)

**Comment by Johni0702** [comment]
Please try to remove as many unrelated third-party mods as possible (ideally only BP+Forgelin).
Also, does this happen reliably?

**Comment by VuDJuBuh** [comment]
So far it's happens 100% of the time and I had to restart the game like 4 times before I got my stuff back so it does.
I'll try removing forgelin and I'm just gonna guess BP is biomes o' plenty.
> Also, does this happen reliably?

**Comment by VuDJuBuh** [comment]
Have tried just BP and forgelin, worked fine.
Have tried pack without BP, also fine.
so there's probably some incompatibility or maybe my 8 GB of ram couldn't keep up when loading my spawn when coming from the nether. but idk witch of both it would be.
I'd have to run through 167 mods (and die in the nether every time) if I wanted to see if there's a compat problem.

**Comment by Johni0702** [comment]
If you throw out half the mods and keep the other half, you could in theory (ignoring other complications like inter-mod-dependencies) get down to it within 8 runs.

The other option for tackling a freeze is by obtaining a stack trace of the game while it's frozen and hoping to find the relevant mod in there. You'll have to find out how to obtain a stack trace by yourself though.

**Comment by VuDJuBuh** [comment]
Little Tiles caused it 100%
ran just BP and LT and it happend.

**Comment by Johni0702** [comment]
This is most likely the same as #225 then. It's also a freeze but happening at a slightly different location (after destroying and re-linking a portal) where it times out after 30 seconds leading to a crash instead.
Because I haven't yet looked into it, I'm keeping this issue open until I'm sure it's the same bug.

**Comment by VirtualGaming1** [comment]
Im having the same issue on first time but was able to run thru when not able to see the other side and I do have LT installed as well and other mods that use Creativecore in my modpack

**Comment by Johni0702** [comment]
@VirtualGaming1 try these: https://github.com/CreativeMD/LittleTiles/issues/237#issuecomment-520828933

Closing because this turned out to be the same issue as the one linked above.

**Comment by VirtualGaming1** [comment]
ok will do and testing it.

**Comment by VirtualGaming1** [comment]
well I just found another one for you and it seem like CorUtil core mod and maybe the Local Weather mod.

This is what show when it got frozen. I had Minecraft debug menu open and using 2839 (The Last 4 Number in the version) of Forge. 
10:50:48.835
Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@60f947e2
10:50:49.035
Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@4b6580dc
10:50:49.240
Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@55aa7e3e
10:50:49.447
Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@15766a64
10:50:49.785
Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@6c37c3dd
10:50:50.134
Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@202249fa
10:50:50.455
Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@31a06c95
10:50:50.721
Swapping main view ClientState for world 0 with ClientState for world -1
10:50:51.188
CoroUtil: resetting rotating particle renderer
10:50:56.345
Ack for swap of -1
10:50:56.509
Respawning magic entity
10:50:56.819
Swapping main view ClientState for world -1 with ClientState for world 0
10:50:58.875
CoroUtil: resetting rotating particle renderer

and here is the freeze happen for about 20 sec or so.
10:53:46.761
NetworkDispatcher exception
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:51)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:417)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:362)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:823)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.flush(NetworkDispatcher.java:555)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:802)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
	at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Johni0702** [comment]
@VirtualGaming1 Please open a separate issue (this one is only for one specific issue with LT), include the full log there and also report the issue to the other mod in question (chances are that they need to make changes to their mod for it to work properly with multiple worlds).
