### ISSUE TITLE
Crashing without starting up - exception maybe clashing with optifine?

### ISSUE THREAD

**Issue by dictator135** [Johni0702/BetterPortals#233]
<details>

```
[05:32:06] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from betterportals-0.2.4.jar
[05:32:06] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in CreativeCore_v1.9.61_mc1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[05:32:06] [main/WARN] [FML]: The coremod com.creativemd.creativecore.core.CreativePatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[05:32:06] [main/WARN] [FML]: The coremod CreativePatchingLoader (com.creativemd.creativecore.core.CreativePatchingLoader) is not signed!
[05:32:06] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in InventoryTweaks-1.63.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[05:32:06] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[05:32:06] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in LittleTiles_v1.5.0-pre157_mc1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[05:32:06] [main/WARN] [FML]: The coremod com.creativemd.littletiles.LittlePatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[05:32:06] [main/WARN] [FML]: The coremod LittlePatchingLoader (com.creativemd.littletiles.LittlePatchingLoader) is not signed!
[05:32:06] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in mclib-1.0.3-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[05:32:06] [main/WARN] [FML]: The coremod McLib core mod (mchorse.mclib.core.McLibCM) is not signed!
[05:32:06] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_E3.jar
[05:32:06] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[05:32:06] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[05:32:07] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users//AppData/Roaming/.minecraft/mods/betterportals-0.2.4.jar Service=LaunchWrapper Env=CLIENT
[05:32:07] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[05:32:07] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[05:32:07] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[05:32:07] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[05:32:07] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[05:32:07] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[05:32:07] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[05:32:07] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ClassTransformer
[05:32:07] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ZIP file: C:\Users\\AppData\Roaming\.minecraft\mods\OptiFine_1.12.2_HD_U_E3.jar
[05:32:07] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[05:32:12] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[05:32:12] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[05:32:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[05:32:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[05:32:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[05:32:13] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[05:32:13] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[05:32:13] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@24097e9b
[05:32:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[05:32:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[05:32:14] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[05:32:14] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[05:32:14] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[05:32:14] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[05:32:14] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[05:32:14] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[05:32:14] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinConfig:onSelect:448]: java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
[05:32:14] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinConfig:onSelect:448]: 	at de.johni0702.minecraft.view.impl.BetterPortalsMixinConfigPlugin.onLoad(BetterPortalsMixinConfigPlugin.kt)
[05:32:14] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinConfig:onSelect:448]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:445)
[05:32:14] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinConfig:onSelect:448]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.selectConfigs(MixinTransformer.java:608)
[05:32:14] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinConfig:onSelect:448]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:570)
[05:32:14] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinConfig:onSelect:448]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548)
[05:32:14] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinConfig:onSelect:448]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451)
[05:32:14] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinConfig:onSelect:448]: 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
[05:32:14] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinConfig:onSelect:448]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[05:32:14] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinConfig:onSelect:448]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[05:32:14] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinConfig:onSelect:448]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[05:32:14] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinConfig:onSelect:448]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[05:32:14] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinConfig:onSelect:448]: 	at java.lang.Class.forName0(Native Method)
[05:32:14] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinConfig:onSelect:448]: 	at java.lang.Class.forName(Class.java:348)
[05:32:14] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinConfig:onSelect:448]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
[05:32:14] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinConfig:onSelect:448]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[05:32:14] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
[05:32:14] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[05:32:14] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[05:32:14] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[05:32:14] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	... 15 more
[05:32:14] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.NullPointerException
[05:32:14] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[05:32:14] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	... 17 more
[05:32:15] [main/INFO] [STDOUT]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [littletiles] Patched net.minecraft.entity.Entity ...
[05:32:15] [main/WARN] [mixin]: Error loading class: io/github/opencubicchunks/cubicchunks/core/server/ChunkGc (java.lang.ClassNotFoundException: The specified class 'io.github.opencubicchunks.cubicchunks.core.server.ChunkGc' was not found)
[05:32:15] [main/WARN] [mixin]: @Mixin target io.github.opencubicchunks.cubicchunks.core.server.ChunkGc was not found mixins.betterportals.view.json:MixinChunkGc_CC
[05:32:15] [main/WARN] [mixin]: Error loading class: io/github/opencubicchunks/cubicchunks/core/server/ColumnWatcher (java.lang.ClassNotFoundException: The specified class 'io.github.opencubicchunks.cubicchunks.core.server.ColumnWatcher' was not found)
[05:32:15] [main/WARN] [mixin]: @Mixin target io.github.opencubicchunks.cubicchunks.core.server.ColumnWatcher was not found mixins.betterportals.view.json:MixinColumnWatcher_CC
[05:32:15] [main/WARN] [mixin]: Error loading class: io/github/opencubicchunks/cubicchunks/core/server/CubeWatcher (java.lang.ClassNotFoundException: The specified class 'io.github.opencubicchunks.cubicchunks.core.server.CubeWatcher' was not found)
[05:32:15] [main/WARN] [mixin]: @Mixin target io.github.opencubicchunks.cubicchunks.core.server.CubeWatcher was not found mixins.betterportals.view.json:MixinCubeWatcher_CC
[05:32:16] [main/INFO] [STDOUT]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [littletiles] Patched net.minecraft.network.NetHandlerPlayServer ...
[05:32:16] [main/WARN] [mixin]: Error loading class: io/github/opencubicchunks/cubicchunks/core/server/PlayerCubeMap (java.lang.ClassNotFoundException: The specified class 'io.github.opencubicchunks.cubicchunks.core.server.PlayerCubeMap' was not found)
[05:32:16] [main/WARN] [mixin]: @Mixin target io.github.opencubicchunks.cubicchunks.core.server.PlayerCubeMap was not found mixins.betterportals.view.json:MixinPlayerCubeMap_CC
[05:32:16] [main/INFO] [STDOUT]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [littletiles] Patched net.minecraft.client.renderer.RenderGlobal ...
[05:32:16] [main/INFO] [STDOUT]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [littletiles] Patched net.minecraft.client.multiplayer.WorldClient ...
[05:32:16] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[05:32:17] [main/INFO] [STDOUT]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [littletiles] Patched net.minecraft.client.Minecraft ...
[05:32:17] [main/INFO] [STDOUT]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [littletiles] Patched net.minecraft.entity.Entity ...
[05:32:18] [main/INFO] [STDOUT]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [littletiles] Patched net.minecraft.entity.player.EntityPlayer ...
[05:32:18] [main/INFO] [STDOUT]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [littletiles] Patched net.minecraft.entity.player.EntityPlayer ...
[05:32:18] [main/INFO] [STDOUT]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [littletiles] Patched net.minecraft.client.multiplayer.WorldClient ...
[05:32:18] [main/INFO] [STDOUT]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [littletiles] Patched net.minecraft.client.Minecraft ...
[05:32:19] [main/INFO] [STDOUT]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [littletiles] Patched net.minecraftforge.client.ForgeHooksClient ...
[05:32:20] [Client thread/INFO] [net.minecraft.client.Minecraft]: Setting user: dictator_of_game
[05:32:21] [Client thread/INFO] [STDOUT]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [littletiles] Patched net.minecraft.util.math.AxisAlignedBB ...
[05:32:24] [Client thread/INFO] [STDOUT]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [littletiles] Patched net.minecraft.entity.player.EntityPlayerMP ...
[05:32:27] [Client thread/INFO] [Config]: [OptiFine] *** Reflector Forge ***
[05:32:27] [Client thread/INFO] [Config]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
[05:32:27] [Client thread/WARN] [mixin]: Error loading class: kotlin/Pair (java.lang.ClassNotFoundException: The specified class 'kotlin.Pair' was not found)
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: java.lang.RuntimeException: java.lang.ClassNotFoundException: kotlin.Pair
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:682)
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:670)
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:267)
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241)
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144)
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:267)
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:158)
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.client.settings.GameSettings.setForgeKeybindProperties(GameSettings.java:3452)
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.client.settings.GameSettings.<init>(GameSettings.java:307)
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:444)
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[05:32:27] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[05:32:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.ClassNotFoundException: kotlin.Pair
[05:32:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	... 27 more
[05:32:28] [Client thread/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.optifine.reflect.Reflector
	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:138) ~[b.class:?]
	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54) ~[b.class:?]
	at net.minecraft.crash.CrashReport.func_85055_a(CrashReport.java:424) ~[b.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:382) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
[05:32:28] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[05:32:28] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[05:32:28] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[05:32:28] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[05:32:28] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
[05:32:28] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[05:32:28] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
</details>

**Comment by Johni0702** [comment]
You're missing Forgelin: https://www.curseforge.com/minecraft/mc-mods/betterportals/relations/dependencies?filter-related-dependencies=3
