### ISSUE TITLE
Minecraft crashes on loading screen with this mod installed.

### ISSUE THREAD

**Issue by GreenGriffin8** [Johni0702/BetterPortals#247]
Using the newest version, 0.2.6, I get the following report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 8/15/19 8:47 PM
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/EntityRenderer
	at net.minecraftforge.client.ForgeHooksClient.shouldUseVanillaReloadableListener(ForgeHooksClient.java:959)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:808)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.EntityRenderer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 22 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 24 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: kotlin.Pair
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:682)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:670)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:267)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:267)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 27 more
Caused by: java.lang.ClassNotFoundException: kotlin.Pair
	... 37 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.ForgeHooksClient.shouldUseVanillaReloadableListener(ForgeHooksClient.java:959)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:808)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 847769040 bytes (808 MB) / 1405091840 bytes (1340 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2836 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID            | Version      | Source                                  | Signature                                |
	|:----- |:------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| L     | minecraft     | 1.12.2       | minecraft.jar                           | None                                     |
	| L     | mcp           | 9.42         | minecraft.jar                           | None                                     |
	| L     | FML           | 8.0.99.99    | forge-1.12.2-14.23.5.2836-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| L     | forge         | 14.23.5.2836 | forge-1.12.2-14.23.5.2836-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| L     | betterportals | 0.2.6        | betterportals-0.2.6.jar                 | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics 4000'
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.4358, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz

**Comment by Johni0702** [comment]
You're missing Forgelin: https://www.curseforge.com/minecraft/mc-mods/betterportals/relations/dependencies?filter-related-dependencies=3

**Comment by Spivyyy** [comment]
> You're missing Forgelin: https://www.curseforge.com/minecraft/mc-mods/betterportals/relations/dependencies?filter-related-dependencies=3

I got the same thing, and downloaded forgelin, but the same thing happens

**Comment by Spivyyy** [comment]
My game crashes on launch as well, here is my crash report.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.3.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.224.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.65-core.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 8/16/19 12:55 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at de.johni0702.minecraft.view.common.ViewAPI$Companion$instance$2.invoke(ViewAPI.kt:25)
	at de.johni0702.minecraft.view.common.ViewAPI$Companion$instance$2.invoke(ViewAPI.kt:22)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at de.johni0702.minecraft.view.common.ViewAPI$Companion.getInstance(ViewAPI.kt)
	at de.johni0702.minecraft.view.client.ClientViewAPI$Companion.getInstance(ClientViewAPI.kt:13)
	at de.johni0702.minecraft.view.client.ClientViewManagerKt.getViewManager(ClientViewManager.kt:35)
	at de.johni0702.minecraft.betterportals.impl.client.audio.PortalAwareSoundManager.recordView(PortalAwareSoundManager.kt:30)
	at net.minecraft.client.audio.SoundManager.handler$recordViewOnPlaySound$zzo000(SoundManager.java:663)
	at net.minecraft.client.audio.SoundManager.func_148611_c(SoundManager.java)
	at net.minecraft.client.audio.SoundHandler.func_147682_a(SoundHandler.java:258)
	at net.minecraft.client.audio.MusicTicker.func_181558_a(SourceFile:49)
	at net.minecraft.client.audio.MusicTicker.func_73660_a(SourceFile:43)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1857)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 439754096 bytes (419 MB) / 771751936 bytes (736 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2823 Optifine OptiFine_1.12.2_HD_U_E3 43 mods loaded, 0 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version                  | Source                                            | Signature                                |
	|:----- |:--------------------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
	|       | minecraft                         | 1.12.2                   | minecraft.jar                                     | None                                     |
	|       | mcp                               | 9.42                     | minecraft.jar                                     | None                                     |
	|       | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2823.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	|       | forge                             | 14.23.5.2823             | forge-1.12.2-14.23.5.2823.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	|       | micdoodlecore                     |                          | minecraft.jar                                     | None                                     |
	|       | aether_legacy                     | 1.4.4                    | aether_legacy-1.12.2-v1.4.4.jar                   | None                                     |
	|       | betterportals                     | 0.2.6                    | betterportals-0.2.6 (2).jar                       | None                                     |
	|       | biomesoplenty                     | 7.0.1.2439               | BiomesOPlenty-1.12.2-7.0.1.2439-universal (1).jar | None                                     |
	|       | chisel                            | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35 (1).jar                  | None                                     |
	|       | ctm                               | MC1.12.2-0.3.3.22        | CTM-MC1.12.2-0.3.3.22.jar                         | None                                     |
	|       | endercore                         | 1.12.2-0.5.65            | EnderCore-1.12.2-0.5.65.jar                       | None                                     |
	|       | enderio                           | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                         | None                                     |
	|       | enderiobase                       | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                         | None                                     |
	|       | enderioconduitsappliedenergistics | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                         | None                                     |
	|       | enderioconduitsopencomputers      | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                         | None                                     |
	|       | enderioconduitsrefinedstorage     | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                         | None                                     |
	|       | enderioconduits                   | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                         | None                                     |
	|       | enderiointegrationforestry        | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                         | None                                     |
	|       | enderiointegrationtic             | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                         | None                                     |
	|       | enderiointegrationticlate         | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                         | None                                     |
	|       | enderiomachines                   | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                         | None                                     |
	|       | enderiopowertools                 | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                         | None                                     |
	|       | forgelin                          | 1.8.3                    | Forgelin-1.8.3.jar                                | None                                     |
	|       | galacticraftplanets               | 4.0.2.220                | Galacticraft-Planets-1.12.2-4.0.2.224.jar         | None                                     |
	|       | galacticraftcore                  | 4.0.2.220                | GalacticraftCore-1.12.2-4.0.2.224.jar             | None                                     |
	|       | waila                             | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                       | None                                     |
	|       | ichunutil                         | 7.2.1                    | iChunUtil-1.12.2-7.2.1 (2).jar                    | None                                     |
	|       | jei                               | 4.15.0.287               | jei_1.12.2-4.15.0.287.jar                         | None                                     |
	|       | journeymap                        | 1.12.2-5.5.5b9           | journeymap-1.12.2-5.5.5b9.jar                     | None                                     |
	|       | lex                               | 1.0.8                    | LibEx-1.12.2-1.0.8 (2).jar                        | None                                     |
	|       | malisiscore                       | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                      | None                                     |
	|       | malisisdoors                      | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                     | None                                     |
	|       | mantle                            | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55 (1).jar                      | None                                     |
	|       | morph                             | 7.1.3                    | Morph-1.12.2-7.1.3 (1).jar                        | None                                     |
	|       | plustic                           | 7.1.1.0                  | plustic-7.1.1.0 (1).jar                           | None                                     |
	|       | plustic                           | 7.1.1.0                  | plustic-7.1.1.0.jar                               | None                                     |
	|       | tconstruct                        | 1.12.2-2.12.0.157        | TConstruct-1.12.2-2.12.0.157 (1).jar              | None                                     |
	|       | tinkersjei                        | 1.2                      | tinkersjei-1.2.jar                                | None                                     |
	|       | tinkertoolleveling                | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0 (1).jar           | None                                     |
	|       | twilightforest                    | 3.8.689                  | twilightforest-1.12.2-3.8.689-universal.jar       | None                                     |
	|       | veinminer                         | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar             | None                                     |
	|       | veinminermodsupport               | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar             | None                                     |
	|       | wawla                             | 2.5.273                  | Wawla-1.12.2-2.5.273.jar                          | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.3.jar)
  
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.224.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
EnderCorePlugin (EnderCore-1.12.2-0.5.65-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 430.64' Renderer: 'GeForce GTX 1050/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2823
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.64, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz

**Comment by Johni0702** [comment]
@Spivyyy That's not the same thing, not even close. Please open a separate issue for it.
In general, tend towards opening a new issue. And if it turns out to be a duplicate, I'll just link you to the original.

Also, before posting the issue, try to remove as many unrelated mods as possible, so only ones relevant to the crash remain.
Also, attach the log file to your issue. It'll likely contain additional, helpful information.
