### ISSUE TITLE
Dying in the nether messes up the local overworld

### ISSUE THREAD

**Issue by SlylyCode** [Johni0702/BetterPortals#26]
When you die in the nether and respawn in the overworld it looks like this:

![2019-05-30_19 21 33](https://user-images.githubusercontent.com/22205057/58651570-ec151c80-8311-11e9-9a5e-6f4e5a9f6488.png)
![2019-05-30_19 21 39](https://user-images.githubusercontent.com/22205057/58651592-f7684800-8311-11e9-8adb-c67b79f7395e.png)

I also saw the biome changing (including the biome "hell") with almost every block, even though the real biome was always "plains".

The exception I got from VanillaFix:
```
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: View id 1 is already taken
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: View id 1 is already taken
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at de.johni0702.minecraft.betterportals.client.view.ViewDemuxingTaskQueue$ViewWrappedFutureTask$1.call(ViewDemuxingTaskQueue.kt:77)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 9 more
Caused by: java.lang.IllegalArgumentException: View id 1 is already taken
    at de.johni0702.minecraft.betterportals.client.view.ClientViewManagerImpl.createView(ClientViewManagerImpl.kt:72)
    at de.johni0702.minecraft.betterportals.net.CreateView$Handler$onMessage$1.invoke(CreateView.kt:59)
    at de.johni0702.minecraft.betterportals.net.CreateView$Handler$onMessage$1.invoke(CreateView.kt:46)
    at de.johni0702.minecraft.betterportals.BetterPortalsModKt$sam$java_lang_Runnable$0.run(BetterPortalsMod.kt)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at de.johni0702.minecraft.betterportals.client.view.ViewDemuxingTaskQueue$ViewWrappedFutureTask$1$1.invoke(ViewDemuxingTaskQueue.kt:75)
    at de.johni0702.minecraft.betterportals.client.view.ViewDemuxingTaskQueue$ViewWrappedFutureTask$1$1.invoke(ViewDemuxingTaskQueue.kt:70)
    at de.johni0702.minecraft.betterportals.client.view.ClientViewManagerImpl.withView(ClientViewManagerImpl.kt:121)
    at de.johni0702.minecraft.betterportals.client.view.ClientView$DefaultImpls.withView(ClientView.kt:10)
    at de.johni0702.minecraft.betterportals.client.view.ClientViewImpl.withView(ClientViewImpl.kt:22)
    at de.johni0702.minecraft.betterportals.client.view.ViewDemuxingTaskQueue$ViewWrappedFutureTask$1.call(ViewDemuxingTaskQueue.kt:74)
    ... 11 more
```

**Comment by Johni0702** [comment]
To clarify: Are this two separate issues or does the dying-in-the-nether-breaks-world issue only happen with vanillafix and the exception is produced at the same time?

**Comment by SlylyCode** [comment]
It happens without VanillaFix too. VanillaFix just gave me the exception so I don't have to search it in the logs.

**Comment by SlylyCode** [comment]
Ok, seems like without VanillaFix I just get hundreds of these exceptions:
```
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: The value 84 is not in the specified inclusive range of 1 to 32
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: The value 84 is not in the specified inclusive range of 1 to 32
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at de.johni0702.minecraft.betterportals.client.view.ViewDemuxingTaskQueue$ViewWrappedFutureTask$1.call(ViewDemuxingTaskQueue.kt:77) ~[ViewDemuxingTaskQueue$ViewWrappedFutureTask$1.class:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
Caused by: java.lang.IllegalArgumentException: The value 84 is not in the specified inclusive range of 1 to 32
	at org.apache.commons.lang3.Validate.inclusiveBetween(Validate.java:1032) ~[commons-lang3-3.5.jar:3.5]
	at net.minecraft.util.BitArray.<init>(SourceFile:14) ~[qw.class:?]
	at net.minecraft.world.chunk.BlockStateContainer.setBits(BlockStateContainer.java:59) ~[axp.class:?]
	at net.minecraft.world.chunk.BlockStateContainer.func_186010_a(BlockStateContainer.java:111) ~[axp.class:?]
	at net.minecraft.world.chunk.Chunk.func_186033_a(Chunk.java:1170) ~[axw.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147263_a(NetHandlerPlayClient.java:745) ~[brz.class:?]
	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:96) ~[je.class:?]
	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:18) ~[je.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at de.johni0702.minecraft.betterportals.client.view.ViewDemuxingTaskQueue$ViewWrappedFutureTask$1$1.invoke(ViewDemuxingTaskQueue.kt:75) ~[ViewDemuxingTaskQueue$ViewWrappedFutureTask$1$1.class:?]
	at de.johni0702.minecraft.betterportals.client.view.ViewDemuxingTaskQueue$ViewWrappedFutureTask$1$1.invoke(ViewDemuxingTaskQueue.kt:70) ~[ViewDemuxingTaskQueue$ViewWrappedFutureTask$1$1.class:?]
	at de.johni0702.minecraft.betterportals.client.view.ClientViewManagerImpl.withView(ClientViewManagerImpl.kt:121) ~[ClientViewManagerImpl.class:?]
	at de.johni0702.minecraft.betterportals.client.view.ClientView$DefaultImpls.withView(ClientView.kt:10) ~[ClientView$DefaultImpls.class:?]
	at de.johni0702.minecraft.betterportals.client.view.ClientViewImpl.withView(ClientViewImpl.kt:22) ~[ClientViewImpl.class:?]
	at de.johni0702.minecraft.betterportals.client.view.ViewDemuxingTaskQueue$ViewWrappedFutureTask$1.call(ViewDemuxingTaskQueue.kt:74) ~[ViewDemuxingTaskQueue$ViewWrappedFutureTask$1.class:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
```
And a couple of these exceptions:
```
[latest.log](https://github.com/Johni0702/BetterPortals/files/3238401/latest.log)

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 16
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 16
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at de.johni0702.minecraft.betterportals.client.view.ViewDemuxingTaskQueue$ViewWrappedFutureTask$1.call(ViewDemuxingTaskQueue.kt:77) ~[ViewDemuxingTaskQueue$ViewWrappedFutureTask$1.class:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 16
	at net.minecraft.world.chunk.BlockStatePaletteLinear.func_186038_a(SourceFile:52) ~[axy.class:?]
	at net.minecraft.world.chunk.BlockStateContainer.func_186010_a(BlockStateContainer.java:114) ~[axp.class:?]
	at net.minecraft.world.chunk.Chunk.func_186033_a(Chunk.java:1170) ~[axw.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147263_a(NetHandlerPlayClient.java:745) ~[brz.class:?]
	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:96) ~[je.class:?]
	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:18) ~[je.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at de.johni0702.minecraft.betterportals.client.view.ViewDemuxingTaskQueue$ViewWrappedFutureTask$1$1.invoke(ViewDemuxingTaskQueue.kt:75) ~[ViewDemuxingTaskQueue$ViewWrappedFutureTask$1$1.class:?]
	at de.johni0702.minecraft.betterportals.client.view.ViewDemuxingTaskQueue$ViewWrappedFutureTask$1$1.invoke(ViewDemuxingTaskQueue.kt:70) ~[ViewDemuxingTaskQueue$ViewWrappedFutureTask$1$1.class:?]
	at de.johni0702.minecraft.betterportals.client.view.ClientViewManagerImpl.withView(ClientViewManagerImpl.kt:121) ~[ClientViewManagerImpl.class:?]
	at de.johni0702.minecraft.betterportals.client.view.ClientView$DefaultImpls.withView(ClientView.kt:10) ~[ClientView$DefaultImpls.class:?]
	at de.johni0702.minecraft.betterportals.client.view.ClientViewImpl.withView(ClientViewImpl.kt:22) ~[ClientViewImpl.class:?]
	at de.johni0702.minecraft.betterportals.client.view.ViewDemuxingTaskQueue$ViewWrappedFutureTask$1.call(ViewDemuxingTaskQueue.kt:74) ~[ViewDemuxingTaskQueue$ViewWrappedFutureTask$1.class:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
```
Here the complete log without any other mods:
[latest.log](https://github.com/Johni0702/BetterPortals/files/3238405/latest.log)
