### ISSUE TITLE
Crash on startup.

### ISSUE THREAD

**Issue by ThatMike12** [Johni0702/BetterPortals#299]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 8/27/19 5:32 AM
Description: Initializing game

java.lang.RuntimeException: Shaders Mod detected. Please remove it, OptiFine has built-in support for shaders.
	at net.optifine.shaders.Shaders.checkShadersModInstalled(Shaders.java:5619)
	at net.optifine.shaders.Shaders.startup(Shaders.java:1853)
	at Config.initDisplay(Config.java:227)
	at net.minecraft.client.renderer.OpenGlHelper.func_77474_a(OpenGlHelper.java:126)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:459)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.optifine.shaders.Shaders.checkShadersModInstalled(Shaders.java:5619)
	at net.optifine.shaders.Shaders.startup(Shaders.java:1853)
	at Config.initDisplay(Config.java:227)
	at net.minecraft.client.renderer.OpenGlHelper.func_77474_a(OpenGlHelper.java:126)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:459)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 338233848 bytes (322 MB) / 536870912 bytes (512 MB) up to 12884901888 bytes (12288 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  org.orecruncher.dsurround.asm.Transformer
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2838
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.4358, Intel
	GL Caps: 
	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>

**Comment by Johni0702** [comment]
It literally tells you what the problem is.
