### ISSUE TITLE
Compact Issue with CoroUtil (Core Mod) and Weather 2 (Local Weather mod)

### ISSUE THREAD

**Issue by VirtualGaming1** [Johni0702/BetterPortals#343]
Forge Version:14.23.5.2839
MC Version: 1.12.2
MODS VERSTION\/
CoroUtil: 1.2.32
Weather 2: 2.6.12
BP: 3.4

will make one for Coro as well

INFO:
well I just found another one for you and it seem like CorUtil core mod and maybe the Local Weather mod.

This is what show when it got frozen. I had Minecraft debug menu open and using 2839 (The Last 4 Number in the version) of Forge.
10:50:48.835
Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@60f947e2
10:50:49.035
Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@4b6580dc
10:50:49.240
Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@55aa7e3e
10:50:49.447
Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@15766a64
10:50:49.785
Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@6c37c3dd
10:50:50.134
Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@202249fa
10:50:50.455
Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@31a06c95
10:50:50.721
Swapping main view ClientState for world 0 with ClientState for world -1
10:50:51.188
CoroUtil: resetting rotating particle renderer
10:50:56.345
Ack for swap of -1
10:50:56.509
Respawning magic entity
10:50:56.819
Swapping main view ClientState for world -1 with ClientState for world 0
10:50:58.875
CoroUtil: resetting rotating particle renderer

and here is the freeze happen for about 20 sec or so.
10:53:46.761
NetworkDispatcher exception
java.io.IOException: An existing connection was forcibly closed by the remote host
at sun.nio.ch.SocketDispatcher.write0(Native Method)
at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
at sun.nio.ch.IOUtil.write(IOUtil.java:51)
at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:417)
at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856)
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:362)
at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:823)
at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1296)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.flush(NetworkDispatcher.java:555)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:802)
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
at java.lang.Thread.run(Thread.java:745)

EDIT: Just found a compact issue with CoroUtil (core mod) and weather2 (Local Weather Mod) it spamming "CoroUtil: resetting rotating particle renderer

And as a Note: on top I am connected to Dedecated server that I have going for my modpack and it spam drop packet when looking thru the portal from the overworld.

**Comment by Karanime** [comment]
I'm getting the same issue. Here's a pastebin of some of the console info: https://pastebin.com/WCT6Hq5h

The client completely freezes up and never crashes to generate a bug report. If this issue can't be addressed, I'll have to uninstall BetterPortals :(
