### ISSUE TITLE
Continues to crash dev environment

### ISSUE THREAD

**Issue by Lumaceon** [Johni0702/BetterPortals#378]
After updating to 0.3.6.1 I'm now getting the following error in my dev environment before MC finishes loading.
Other than the version, same settings as #372.
```
[23:51:19] [Client thread/FATAL] [minecraft/Minecraft]: Unreported exception thrown!
kotlin.KotlinNullPointerException: null
	at de.johni0702.minecraft.view.common.ViewAPI$Companion$instance$2.invoke(ViewAPI.kt:23) ~[ViewAPI$Companion$instance$2.class:?]
	at de.johni0702.minecraft.view.common.ViewAPI$Companion$instance$2.invoke(ViewAPI.kt:20) ~[ViewAPI$Companion$instance$2.class:?]
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[SynchronizedLazyImpl.class:1.3.50-release-112 (1.3.50)]
	at de.johni0702.minecraft.view.common.ViewAPI$Companion.getInstance(ViewAPI.kt) ~[ViewAPI$Companion.class:?]
	at de.johni0702.minecraft.view.client.ClientViewAPI$Companion.getInstance(ClientViewAPI.kt:13) ~[ClientViewAPI$Companion.class:?]
	at de.johni0702.minecraft.view.client.ClientWorldsManagerKt.getWorldsManager(ClientWorldsManager.kt:43) ~[ClientWorldsManagerKt.class:?]
	at de.johni0702.minecraft.betterportals.impl.client.audio.PortalAwareSoundManager.recordView(PortalAwareSoundManager.kt:30) ~[PortalAwareSoundManager.class:?]
	at net.minecraft.client.audio.SoundManager.handler$recordViewOnPlaySound$zzf000(SoundManager.java:698) ~[SoundManager.class:?]
	at net.minecraft.client.audio.SoundManager.playSound(SoundManager.java) ~[SoundManager.class:?]
	at net.minecraft.client.audio.SoundHandler.playSound(SoundHandler.java:261) ~[SoundHandler.class:?]
	at net.minecraft.client.audio.MusicTicker.playMusic(MusicTicker.java:61) ~[MusicTicker.class:?]
	at net.minecraft.client.audio.MusicTicker.update(MusicTicker.java:51) ~[MusicTicker.class:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1984) ~[Minecraft.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1188) ~[Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:442) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:25) [start/:?]
```

**Comment by Johni0702** [comment]
Looks like an issue with CF's maven repo or FG this time.

For some reason FG doesn't actually deobfuscate the jar when it's being pulled from CF.
Installing the same (!) jar into your local maven repository and using `mavenLocal()` instead of the CF repo, FG will properly deobfuscate the jar.

No idea why that's the case and both, CF and FG, have quite frankly each wasted far too much of my hours already so I'm not going to find out myself.

```
wget https://minecraft.curseforge.com/api/maven/betterportals/BetterPortals/0.3.6.1/BetterPortals-0.3.6.1.jar
mvn install:install-file -Dfile=build/libs/betterportals-0.3.6.1.jar -DgroupId=betterportals -DartifactId=BetterPortals -Dversion=0.3.6.1 -Dpackaging=jar
rm ~/.gradle/caches/minecraft/deobfedDeps/deobf/betterportals/ -r
# Refresh project
```
