### ISSUE TITLE
Mod does not work on servers

### ISSUE THREAD

**Issue by TheD0ct0r101** [Johni0702/BetterPortals#38]
So I tested the mod (0.1.3) in the Enigmatica 2 Modpack in singleplayer and it works fine, however, when running on a dedicated server, the portal appears black and you can not walk through it. Its like a solid wall.

**Comment by Johni0702** [comment]
Are there any errors in the console?

**Comment by TheD0ct0r101** [comment]
Theres no crash log as a result from this, however, with my limited knowledge of java code, I think I found the part of the log containing the betterportals error. This passage from the log goes from when I joined the world to when I tried to reignite the portal to me leaving the server:
`[19:59:49] [Server thread/INFO] [THAUMCRAFT]: Creating aura cache for world -1
[19:59:50] [Thread-43/INFO] [THAUMCRAFT]: Starting aura thread for dim -1
[19:59:52] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.EntityJoinWorldEvent@69df7ad5:
java.lang.NullPointerException: null
	at journeymap.server.events.ForgeEvents.on(ForgeEvents.java:39) ~[ForgeEvents.class:1.12.2-5.5.4]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2378_ForgeEvents_on_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraft.world.World.func_72838_d(World.java:1206) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058) [oo.class:?]
	at de.johni0702.minecraft.betterportals.server.view.ServerViewManagerImpl.createView(ServerViewManagerImpl.kt:74) [ServerViewManagerImpl.class:?]
	at de.johni0702.minecraft.betterportals.server.view.ServerViewManager$DefaultImpls.createView$default(ServerViewManager.kt:30) [ServerViewManager$DefaultImpls.class:?]
	at de.johni0702.minecraft.betterportals.common.entity.AbstractPortalEntity.func_184178_b(AbstractPortalEntity.kt:436) [AbstractPortalEntity.class:?]
	at de.johni0702.minecraft.betterportals.common.entity.AbstractPortalEntity.link(AbstractPortalEntity.kt:476) [AbstractPortalEntity.class:?]
	at de.johni0702.minecraft.betterportals.common.blocks.PortalBlock$tryToLinkPortals$2.apply(PortalBlock.kt:115) [PortalBlock$tryToLinkPortals$2.class:?]
	at de.johni0702.minecraft.betterportals.common.blocks.PortalBlock$tryToLinkPortals$2.apply(PortalBlock.kt:26) [PortalBlock$tryToLinkPortals$2.class:?]
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_202]
	at net.minecraft.server.MinecraftServer.func_175586_a(MinecraftServer.java:1383) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_152344_a(MinecraftServer.java:1395) [MinecraftServer.class:?]
	at de.johni0702.minecraft.betterportals.common.blocks.PortalBlock$tryToLinkPortals$3.execute(PortalBlock.kt:117) [PortalBlock$tryToLinkPortals$3.class:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_202]
	at net.minecraft.server.MinecraftServer.func_175586_a(MinecraftServer.java:1383) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_152344_a(MinecraftServer.java:1395) [MinecraftServer.class:?]
	at de.johni0702.minecraft.betterportals.common.blocks.PortalBlock$findOrCreateRemotePortal$5.execute(PortalBlock.kt:263) [PortalBlock$findOrCreateRemotePortal$5.class:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_202]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
[19:59:52] [Server thread/ERROR] [FML]: Index: 52 Listeners:
[19:59:52] [Server thread/ERROR] [FML]: 0: HIGHEST
[19:59:52] [Server thread/ERROR] [FML]: 1: ASM: net.minecraftforge.common.ForgeInternalHandler@34276df4 onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 2: ASM: hellfirepvp.astralsorcery.common.util.BlockDropCaptureAssist@12729292 onDrop(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 3: HIGH
[19:59:52] [Server thread/ERROR] [FML]: 4: ASM: hellfirepvp.astralsorcery.common.constellation.perk.attribute.type.AttributeCritChance@dc154bd7 onArrowCt(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 5: ASM: tschipp.carryon.common.event.ItemEvents@2599c9df onItemDropped(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 6: ASM: tschipp.carryon.common.event.ItemEntityEvents@543de4e0 onItemDropped(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 7: NORMAL
[19:59:52] [Server thread/ERROR] [FML]: 8: ASM: class thaumcraft.common.lib.events.EntityEvents entitySpawns(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 9: ASM: class thaumcraft.common.lib.events.PlayerEvents playerJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 10: ASM: class crazypants.enderio.base.handler.darksteel.PlayerAOEAttributeHandler handleJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 11: ASM: class amerifrance.guideapi.util.EventHandler onPlayerJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 12: ASM: class WayofTime.bloodmagic.util.handler.event.LivingArmourHandler onEntityJoinedWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 13: ASM: class link.infra.demagnetize.blocks.DemagnetizerEventHandler itemSpawned(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 14: ASM: class com.feed_the_beast.ftbutilities.handlers.FTBUtilitiesWorldEventHandler onMobSpawned(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 15: ASM: class flaxbeard.immersivepetroleum.common.EventHandler onEntityJoiningWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 16: ASM: com.minecolonies.coremod.event.BarbarianSpawnEventHandler@2a6122cb onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 17: ASM: class com.cazsius.solcarrot.handler.CapabilityHandler onPlayerLogin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 18: ASM: shadows.fastbench.FastBench@19861798 normalRemoval(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 19: ASM: baubles.common.event.EventHandlerEntity@44100ba playerJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 20: ASM: biomesoplenty.common.handler.SheepEventHandler@129decca onEntityJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 21: ASM: com.animania.common.events.EventReplaceSpawnAnimals@28d69fda onEntitySpawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 22: ASM: com.animania.common.events.EntityEventHandler@58545c0f onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 23: ASM: com.animania.common.events.CapabilityLoadHandler@345b3cc0 entityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 24: ASM: hellfirepvp.astralsorcery.common.constellation.perk.attribute.type.AttributeArrowSpeed@b96d0033 onArrowFire(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 25: ASM: jds.bibliocraft.events.EventSpawn@7bed7b40 onSpawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 26: ASM: forestry.core.EventHandlerCore@54dd797f handleVillagerAI(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 27: ASM: com.blamejared.clumps.events.CommonEventHandler@10d6e101 updateEntities(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 28: ASM: teamroots.embers.research.ResearchManager@f462475 onJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 29: ASM: com.phylogeny.extrabitmanipulation.armor.capability.ChiseledArmorSlotsEventHandler@5d455bd1 markPlayerSlotsDirty(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 30: ASM: com.rwtema.extrautils2.items.DemonicIngotHandler@f155f81 onJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 31: ASM: com.rwtema.extrautils2.blocks.BlockCursedEarth$EventHandler@76c67cab spawnInWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 32: ASM: net.blay09.mods.horsetweaks.SyncHorseDataHandler@c34d68a onHorseSpawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 33: ASM: ca.wescook.nutrition.events.EventPlayerJoinWorld@1afc9f58 EntityJoinWorldEvent(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 34: ASM: openmods.entity.DelayedEntityLoadManager@701d4740 onEntityCreate(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 35: ASM: openmods.world.DropCapture@33dcde0d onEntityConstruct(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 36: ASM: openblocks.common.LuggageDropHandler@7fcd45db onItemDrop(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 37: ASM: openblocks.common.EntityEventHandler@3f8e0365 onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 38: ASM: me.desht.pneumaticcraft.common.event.EventHandlerPneumaticCraft@6fb124d0 onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 39: ASM: ivorius.reccomplex.events.handlers.RCForgeEventHandler@5ee63645 onEntityDrop(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 40: ASM: mcjty.rftoolsdim.ForgeEventHandlers@600bb7fd onEntityJoinWorldEvent(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 41: ASM: bq_standard.handlers.EventHandler@1ab21147 onEntityCreated(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 42: ASM: com.teamwizardry.wizardry.common.core.EventHandler@43089155 redstoneHandler(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 43: ASM: mekanism.common.item.ItemBlockCardboardBox@6a1400f1 onEntitySpawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 44: ASM: class com.enderio.core.common.handlers.XPBoostHandler handleArrowFire(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 45: ASM: hellfirepvp.astralsorcery.common.event.listener.EventHandlerEntity@1ecd8e77 onSpawnDropCloud(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 46: ASM: com.lothrazar.cyclicmagic.event.EventPlayerData@165e1f2d onJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 47: ASM: Block{cyclicmagic:imbuer} onJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 48: ASM: class com.rwtema.careerbees.effects.EffectDigging captureStacks(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 49: ASM: li.cil.oc.common.EventHandler$@7f2642ca onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 50: ASM: blusunrize.immersiveengineering.common.EventHandler@c550f37 onEntityJoiningWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 51: ASM: mcjty.incontrol.ForgeEventHandlers@64ee240f onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 52: ASM: journeymap.server.events.ForgeEvents@7b8b440b on(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 53: ASM: com.m4thg33k.tombmanygraves.friends.FriendHandler@57e2b06b onPlayerJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 54: ASM: com.builtbroken.ai.improvements.AIImprovements@2f4ec3df onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 55: ASM: com.rwtema.extrautils2.villagers.EntityAINinjaPoof$Handler@292d18ea a(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 56: LOW
[19:59:52] [Server thread/ERROR] [FML]: 57: ASM: com.brandon3055.brandonscore.handlers.BCEventHandler@325819d4 entityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 58: LOWEST
[19:59:52] [Server thread/ERROR] [FML]: 59: ASM: class dan200.computercraft.shared.util.DropConsumer onEntitySpawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 60: ASM: net.shadowmage.ancientwarfare.npc.event.EventHandler@3b0d41ad onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 61: ASM: hellfirepvp.astralsorcery.common.constellation.perk.attribute.type.AttributeCritMultiplier@8bcd7c54 onArrowCt(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [FML]: 62: ASM: oreexcavation.handlers.EventHandler@327b7e65 onEntitySpawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[19:59:52] [Server thread/ERROR] [betterportals]: Catching
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_202]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_202]
	at net.minecraft.server.MinecraftServer.func_175586_a(MinecraftServer.java:1383) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_152344_a(MinecraftServer.java:1395) [MinecraftServer.class:?]
	at de.johni0702.minecraft.betterportals.common.blocks.PortalBlock$tryToLinkPortals$3.execute(PortalBlock.kt:117) [PortalBlock$tryToLinkPortals$3.class:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_202]
	at net.minecraft.server.MinecraftServer.func_175586_a(MinecraftServer.java:1383) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_152344_a(MinecraftServer.java:1395) [MinecraftServer.class:?]
	at de.johni0702.minecraft.betterportals.common.blocks.PortalBlock$findOrCreateRemotePortal$5.execute(PortalBlock.kt:263) [PortalBlock$findOrCreateRemotePortal$5.class:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_202]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
Caused by: java.lang.NullPointerException
	at journeymap.server.events.ForgeEvents.on(ForgeEvents.java:39) ~[ForgeEvents.class:1.12.2-5.5.4]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2378_ForgeEvents_on_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraft.world.World.func_72838_d(World.java:1206) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058) ~[oo.class:?]
	at de.johni0702.minecraft.betterportals.server.view.ServerViewManagerImpl.createView(ServerViewManagerImpl.kt:74) ~[ServerViewManagerImpl.class:?]
	at de.johni0702.minecraft.betterportals.server.view.ServerViewManager$DefaultImpls.createView$default(ServerViewManager.kt:30) ~[ServerViewManager$DefaultImpls.class:?]
	at de.johni0702.minecraft.betterportals.common.entity.AbstractPortalEntity.func_184178_b(AbstractPortalEntity.kt:436) ~[AbstractPortalEntity.class:?]
	at de.johni0702.minecraft.betterportals.common.entity.AbstractPortalEntity.link(AbstractPortalEntity.kt:476) ~[AbstractPortalEntity.class:?]
	at de.johni0702.minecraft.betterportals.common.blocks.PortalBlock$tryToLinkPortals$2.apply(PortalBlock.kt:115) ~[PortalBlock$tryToLinkPortals$2.class:?]
	at de.johni0702.minecraft.betterportals.common.blocks.PortalBlock$tryToLinkPortals$2.apply(PortalBlock.kt:26) ~[PortalBlock$tryToLinkPortals$2.class:?]
	... 33 more
[20:02:43] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: _TheD0ct0r_ lost connection: Disconnected`

**Comment by Johni0702** [comment]
This appears to be an issue with (server-side) JourneyMap.
There was a significant change to the code which caused the crash in JourneyMap 1.12.2-5.5.5b9, could you try updating to that (or a more recent version) and check if it works?
