### ISSUE TITLE
Server crashes when teleporting between dimensions with waystones

### ISSUE THREAD

**Issue by PikachuMC99** [Johni0702/BetterPortals#401]
The same server and modlist as #400 but this time when anyone tries to tp from one dimension to another with a waystone or warp stone from the waystones mod the player gets teleported but the server crashes instantly.

**Comment by Johni0702** [comment]
Please attach the crash report. I may be able to tell what's going on without having to install potentially dozens of mods myself.

**Comment by alpharou** [comment]
I'll post a crash for you. Same thing happens to me.

It crashes when teleporting between dimensions, same dimension works fine, independently if there is portals nearby or not.

```
[20:49:45] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@158ef58:
java.lang.IllegalStateException: Player changed world without us noticing. Did some third-party mod do something weird?
        at de.johni0702.minecraft.view.impl.server.ServerWorldsManagerImpl.updateActiveViews(ServerWorldsManagerImpl.kt:67) ~[ServerWorldsManagerImpl.class:?]
        at net.minecraft.server.management.PlayerChunkMap.handler$updateMovingPlayerWithViews$zzd000(SourceFile:597) ~[ou.class:?]
        at net.minecraft.server.management.PlayerChunkMap.func_72685_d(SourceFile) ~[ou.class:?]
        at de.johni0702.minecraft.view.impl.server.ServerWorldsManagerImpl.tick(ServerWorldsManagerImpl.kt:264) ~[ServerWorldsManagerImpl.class:?]
        at de.johni0702.minecraft.view.impl.server.ServerWorldsManagerImpl.access$tick(ServerWorldsManagerImpl.kt:36) ~[ServerWorldsManagerImpl.class:?]
        at de.johni0702.minecraft.view.impl.server.ServerWorldsManagerImpl$EventHandler.postTick(ServerWorldsManagerImpl.kt:325) ~[ServerWorldsManagerImpl$EventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_335_EventHandler_postTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[20:49:45] [Server thread/ERROR] [FML]: Index: 6 Listeners:
[20:49:45] [Server thread/ERROR] [FML]: 0: NORMAL
[20:49:45] [Server thread/ERROR] [FML]: 1: ASM: class blusunrize.immersiveengineering.common.blocks.BlockIETileProvider onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:49:45] [Server thread/ERROR] [FML]: 2: ASM: net.minecraftforge.common.ForgeInternalHandler@61fc8 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:49:45] [Server thread/ERROR] [FML]: 3: ASM: pl.asie.charset.lib.notify.NotifyImplementation@de36eb updateRecuringNotifications(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:49:45] [Server thread/ERROR] [FML]: 4: ASM: mcmultipart.MCMPCommonProxy@1536866 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:49:45] [Server thread/ERROR] [FML]: 5: ASM: hellfirepvp.astralsorcery.common.auxiliary.tick.TickManager@1ab1113 serverTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:49:45] [Server thread/ERROR] [FML]: 6: ASM: de.johni0702.minecraft.view.impl.server.ServerWorldsManagerImpl$EventHandler@dd9d7 postTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:49:45] [Server thread/ERROR] [FML]: 7: ASM: appeng.hooks.TickHandler@bf35df onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[20:49:45] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.IllegalStateException: Player changed world without us noticing. Did some third-party mod do something weird?
        at de.johni0702.minecraft.view.impl.server.ServerWorldsManagerImpl.updateActiveViews(ServerWorldsManagerImpl.kt:67) ~[ServerWorldsManagerImpl.class:?]
        at net.minecraft.server.management.PlayerChunkMap.handler$updateMovingPlayerWithViews$zzd000(SourceFile:597) ~[ou.class:?]
        at net.minecraft.server.management.PlayerChunkMap.func_72685_d(SourceFile) ~[ou.class:?]
        at de.johni0702.minecraft.view.impl.server.ServerWorldsManagerImpl.tick(ServerWorldsManagerImpl.kt:264) ~[ServerWorldsManagerImpl.class:?]
        at de.johni0702.minecraft.view.impl.server.ServerWorldsManagerImpl.access$tick(ServerWorldsManagerImpl.kt:36) ~[ServerWorldsManagerImpl.class:?]
        at de.johni0702.minecraft.view.impl.server.ServerWorldsManagerImpl$EventHandler.postTick(ServerWorldsManagerImpl.kt:325) ~[ServerWorldsManagerImpl$EventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_335_EventHandler_postTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
```

**Comment by Johni0702** [comment]
@alpharou Thanks for the log.
I've identified the issue by looking at the source code of Waystones. The issue needs to be fixed in Waystones, so I've created a ticket on its issue tracker (see above).
