### ISSUE TITLE
Doesnt work at all, nether portal crashes, end portal shows small window on the left side of the screen

### ISSUE THREAD

**Issue by Achronox** [Johni0702/BetterPortals#407]

**Comment by Achronox** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (shadowfacts-forgelin-1_12_2.jar)
  TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 11/6/19 5:46 PM
Description: Exception ticking world

java.lang.NoClassDefFoundError: kotlin/math/MathKt
	at de.johni0702.minecraft.betterportals.common.block.PortalBlock$DefaultImpls.findOrCreateRemotePortal(PortalBlock.kt:152)
	at de.johni0702.minecraft.betterportals.impl.vanilla.common.blocks.BlockBetterNetherPortal.findOrCreateRemotePortal(BlockBetterNetherPortal.kt:23)
	at de.johni0702.minecraft.betterportals.common.block.PortalBlock$DefaultImpls.tryToLinkPortals(PortalBlock.kt:100)
	at de.johni0702.minecraft.betterportals.impl.vanilla.common.blocks.BlockBetterNetherPortal.tryToLinkPortals(BlockBetterNetherPortal.kt:23)
	at de.johni0702.minecraft.betterportals.impl.vanilla.common.blocks.BlockBetterNetherPortal.func_176548_d(BlockBetterNetherPortal.kt:61)
	at net.minecraft.block.BlockFire.func_176213_c(BlockFire.java:363)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockFire.func_180650_b(BlockFire.java:158)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at de.johni0702.minecraft.betterportals.common.block.PortalBlock$DefaultImpls.findOrCreateRemotePortal(PortalBlock.kt:152)
	at de.johni0702.minecraft.betterportals.impl.vanilla.common.blocks.BlockBetterNetherPortal.findOrCreateRemotePortal(BlockBetterNetherPortal.kt:23)
	at de.johni0702.minecraft.betterportals.common.block.PortalBlock$DefaultImpls.tryToLinkPortals(PortalBlock.kt:100)
	at de.johni0702.minecraft.betterportals.impl.vanilla.common.blocks.BlockBetterNetherPortal.tryToLinkPortals(BlockBetterNetherPortal.kt:23)
	at de.johni0702.minecraft.betterportals.impl.vanilla.common.blocks.BlockBetterNetherPortal.func_176548_d(BlockBetterNetherPortal.kt:61)
	at net.minecraft.block.BlockFire.func_176213_c(BlockFire.java:363)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockFire.func_180650_b(BlockFire.java:158)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)

-- Affected level --
Details:
	Level name: Новый мир------------
	All players: 1 total; [EntityPlayerMP['Achronox'/182, l='Новый мир------------', x=40.47, y=83.00, z=-73.33]]
	Chunk stats: ServerChunkCache: 289 Drop: 0
	Level seed: -7856294261371132725
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (41,64,-79), Chunk: (at 9,4,1 in 2,-5; contains blocks 32,0,-80 to 47,255,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 4306 game time, 4306 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 47972 (now: false), thunder time: 148185 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 202202264 bytes (192 MB) / 523358208 bytes (499 MB) up to 8457027584 bytes (8065 MB)
	JVM Flags: 3 total; -Xmn128M -Xmx8077M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                         | Version      | Source                          | Signature |
	|:------ |:-------------------------- |:------------ |:------------------------------- |:--------- |
	| LCHIJA | minecraft                  | 1.12.2       | minecraft.jar                   | None      |
	| LCHIJA | mcp                        | 9.42         | minecraft.jar                   | None      |
	| LCHIJA | FML                        | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar   | None      |
	| LCHIJA | forge                      | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar   | None      |
	| LCHIJA | forgelin                   | 1.5.1        | shadowfacts-forgelin-1_12_2.jar | None      |
	| LCHIJA | betterportals              | 0.2.7        | Better-Portals-Mod-1.12.2.jar   | None      |
	| LCHIJA | tlauncher_custom_cape_skin | 1.4          | tlskincape_1.12.2-1.4.jar       | None      |

	Loaded coremods (and transformers): 
ForgelinPlugin (shadowfacts-forgelin-1_12_2.jar)
  
TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Achronox'/182, l='Новый мир------------', x=40.47, y=83.00, z=-73.33]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Johni0702** [comment]
The version of Forgelin you're using is outdated by two and a half years (and that's probably the source of the crash).
The version of BP you're using is also fairly outdated (there has been one fundamental re-design of its entire architecture since then).

If the small window issue persists with updated versions, please post a screenshot of it and attach the game log.
