### ISSUE TITLE
Portal Immediately Closing after activation

### ISSUE THREAD

**Issue by judicius** [Johni0702/BetterPortals#446]
When trying to open a nether portal the portal opens and then closes. The console reports the following.

Forge - 14.23.5.2847
BP Version 0.3.7.4

server config https://pastebin.com/1Fh9AH4U

Running Mod Pack The Builders Delight. TF portals disabled, third party enhancement enabled.

```
07.01 14:07:09 [Server] Server thread/INFO [FML]: Loading dimension -1 (Vox) (net.minecraft.server.dedicated.DedicatedServer@70989e1e)
07.01 14:07:09 [Server] Server thread/INFO [dsurround]: Attaching capabilities to world [the_nether] (SERVER)
07.01 14:07:09 [Server] Server thread/INFO [dsurround]: DimensionInfo{id=-1, name=the_nether, seaLevel=0, cloudHeight=128, skyHeight=128, haze=false, aurora=false, weather=true, fog=true}
07.01 14:07:09 [Server] Server thread/INFO [dsurround]: Creating NETHER weather generator for dimension [the_nether]
07.01 14:07:11 [Server] Server thread/ERROR [FML]: Exception caught during firing event net.minecraftforge.event.entity.EntityJoinWorldEvent@559fffad:
07.01 14:07:11 [Server] INFO java.lang.NullPointerException: null
07.01 14:07:11 [Server] INFO at journeymap.common.network.impl.MessageProcessor.sendToPlayer(MessageProcessor.java:240) ~[MessageProcessor.class:1.12.2-5.5.6]
07.01 14:07:11 [Server] INFO at journeymap.server.events.ForgeEvents.sendConfigsToPlayer(ForgeEvents.java:82) ~[ForgeEvents.class:1.12.2-5.5.6]
07.01 14:07:11 [Server] INFO at journeymap.server.events.ForgeEvents.onEntityJoinWorldEvent(ForgeEvents.java:64) ~[ForgeEvents.class:1.12.2-5.5.6]
07.01 14:07:11 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1077_ForgeEvents_onEntityJoinWorldEvent_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?]
07.01 14:07:11 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
07.01 14:07:11 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
07.01 14:07:11 [Server] INFO at farseek.world.gen.structure.package$.post(package.scala:38) [package$.class:?]
07.01 14:07:11 [Server] INFO at farseek.world.gen.structure.package.post(package.scala) [package.class:?]
07.01 14:07:11 [Server] INFO at net.minecraft.world.World.func_72838_d(World.java:1209) [amu.class:?]
07.01 14:07:11 [Server] INFO at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058) [oo.class:?]
07.01 14:07:11 [Server] INFO at de.johni0702.minecraft.view.impl.server.ServerWorldsManagerImpl.createWorldManager(ServerWorldsManagerImpl.kt:206) [ServerWorldsManagerImpl.class:?]
07.01 14:07:11 [Server] INFO at de.johni0702.minecraft.view.impl.server.ServerWorldsManagerImpl.getOrCreateWorldManager(ServerWorldsManagerImpl.kt:178) [ServerWorldsManagerImpl.class:?]
07.01 14:07:11 [Server] INFO at de.johni0702.minecraft.view.impl.server.ServerWorldsManagerImpl.registerView(ServerWorldsManagerImpl.kt:54) [ServerWorldsManagerImpl.class:?]
07.01 14:07:11 [Server] INFO at de.johni0702.minecraft.view.server.ServerWorldsManager$DefaultImpls.createView(ServerWorldsManager.kt:32) [ServerWorldsManager$DefaultImpls.class:?]
07.01 14:07:11 [Server] INFO at de.johni0702.minecraft.view.impl.server.ServerWorldsManagerImpl.createView(ServerWorldsManagerImpl.kt:35) [ServerWorldsManagerImpl.class:?]
07.01 14:07:11 [Server] INFO at de.johni0702.minecraft.betterportals.common.PortalAgent.registerView(PortalAgent.kt:543) [PortalAgent.class:?]
07.01 14:07:11 [Server] INFO at de.johni0702.minecraft.betterportals.common.PortalAgent.addTrackingPlayer(PortalAgent.kt:536) [PortalAgent.class:?]
07.01 14:07:11 [Server] INFO at de.johni0702.minecraft.betterportals.common.PortalAgent.updateViews(PortalAgent.kt:557) [PortalAgent.class:?]
07.01 14:07:11 [Server] INFO at de.johni0702.minecraft.betterportals.common.PortalAgent.setPortal(PortalAgent.kt:136) [PortalAgent.class:?]
07.01 14:07:11 [Server] INFO at de.johni0702.minecraft.betterportals.common.entity.AbstractPortalEntity.setPortal(AbstractPortalEntity.kt:62) [AbstractPortalEntity.class:?]
07.01 14:07:11 [Server] INFO at de.johni0702.minecraft.betterportals.common.entity.AbstractPortalEntity.link(AbstractPortalEntity.kt:144) [AbstractPortalEntity.class:?]
07.01 14:07:11 [Server] INFO at de.johni0702.minecraft.betterportals.common.block.PortalBlock$tryToLinkPortals$2.accept(PortalBlock.kt:125) [PortalBlock$tryToLinkPortals$2.class:?]
07.01 14:07:11 [Server] INFO at de.johni0702.minecraft.betterportals.common.block.PortalBlock$tryToLinkPortals$2.accept(PortalBlock.kt:25) [PortalBlock$tryToLinkPortals$2.class:?]
07.01 14:07:11 [Server] INFO at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) [?:1.8.0_222]
07.01 14:07:11 [Server] INFO at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) [?:1.8.0_222]
07.01 14:07:11 [Server] INFO at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) [?:1.8.0_222]
07.01 14:07:11 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
07.01 14:07:11 [Server] INFO at net.minecraft.server.MinecraftServer.func_175586_a(MinecraftServer.java:1383) [MinecraftServer.class:?]
```

**Comment by Johni0702** [comment]
Looks like #198.
Since you didn't specify which version of journeymap you're using, I'm going to assume it is and close this issue for now.
If it is not, please attach the full server log file.
