### ISSUE TITLE
Game crash when loading

### ISSUE THREAD

**Issue by DenisTheZiwward** [Johni0702/BetterPortals#468]
---- Minecraft Crash Report ----
// Don't do that.

Time: 2020-02-15 15:43:12 EET
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Better Portals (betterportals)
Caused by: java.lang.ExceptionInInitializerError
    at de.johni0702.minecraft.view.impl.ClientViewAPIImpl.init(ViewAPIImpl.kt:47)
    at de.johni0702.minecraft.view.impl.common.ExtensionsKt$initView$2.invoke(Extensions.kt:28)
    at de.johni0702.minecraft.view.impl.common.ExtensionsKt$initView$2.invoke(Extensions.kt)
    at de.johni0702.minecraft.betterportals.impl.BetterPortalsMod$ClientProxy.init(BetterPortalsMod.kt:214)
    at de.johni0702.minecraft.betterportals.impl.BetterPortalsMod.init(BetterPortalsMod.kt:154)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.optifine.shaders.Shaders
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at de.johni0702.minecraft.view.impl.compat.OptifineReflection.<init>(Optifine.kt:27)
    at de.johni0702.minecraft.view.impl.compat.OptifineKt.<clinit>(Optifine.kt:36)
    ... 45 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 194348584 bytes (185 MB) / 771751936 bytes (736 MB) up to 2147483648 bytes (2048 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_C6 37 mods loaded, 37 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                  | Version         | Source                                  | Signature                                |
       |:----- |:------------------- |:--------------- |:--------------------------------------- |:---------------------------------------- |
       | LCHI  | minecraft           | 1.12.2          | minecraft.jar                           | None                                     |
       | LCHI  | mcp                 | 9.42            | minecraft.jar                           | None                                     |
       | LCHI  | FML                 | 8.0.99.99       | forge-1.12.2-14.23.5.2847.jar           | None                                     |
       | LCHI  | forge               | 14.23.5.2847    | forge-1.12.2-14.23.5.2847.jar           | None                                     |
       | LCHI  | dsurroundcore       | 3.5.4.3         | minecraft.jar                           | None                                     |
       | LCHI  | betternether        | 0.1.8.6         | Better-Nether-Mod-1.12.2.jar            | None                                     |
       | LCHI  | bettercaves         | 1.12.2          | bettercaves-1.12.2-1.6.0.jar            | None                                     |
       | LCHI  | forgelin            | 1.8.4           | Forgelin-1.8.4.jar                      | None                                     |
       | LCHE  | betterportals       | 0.3.7.5         | betterportals-0.3.7.5.jar               | None                                     |
       | LCH   | buildcraftlib       | 7.99.24.1       | BuildCraft-Mod-1.12.2.jar               | None                                     |
       | LCH   | buildcraftcore      | 7.99.24.1       | BuildCraft-Mod-1.12.2.jar               | None                                     |
       | LCH   | buildcraftbuilders  | 7.99.24.1       | BuildCraft-Mod-1.12.2.jar               | None                                     |
       | LCH   | buildcrafttransport | 7.99.24.1       | BuildCraft-Mod-1.12.2.jar               | None                                     |
       | LCH   | buildcraftsilicon   | 7.99.24.1       | BuildCraft-Mod-1.12.2.jar               | None                                     |
       | LCH   | buildcraftcompat    | 7.99.24.1       | BuildCraft-Mod-1.12.2.jar               | None                                     |
       | LCH   | buildcraftenergy    | 7.99.24.1       | BuildCraft-Mod-1.12.2.jar               | None                                     |
       | LCH   | buildcraftfactory   | 7.99.24.1       | BuildCraft-Mod-1.12.2.jar               | None                                     |
       | LCH   | buildcraftrobotics  | 7.99.24.1       | BuildCraft-Mod-1.12.2.jar               | None                                     |
       | LCH   | chameleon           | 1.12-4.1.3      | Chameleon-Library-1.12.jar              | None                                     |
       | LCH   | codechickenlib      | 3.2.2.353       | CodeChickenLib-1.12.2.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | craftstudioapi      | 1.0.0           | CraftStudio-1.0.0.93-mc1.12-alpha.jar   | None                                     |
       | LCH   | customspawner       | 3.11.4          | Custom-Mob-Spawner-Mod-1.12.2.jar       | None                                     |
       | LCH   | dynamictrees        | 1.12.2-0.9.5    | Dynamic-Trees-Mod-1.12.2 (1).jar        | None                                     |
       | LCH   | waila               | 1.8.26          | Hwyla-Mod-1.12.2.jar                    | None                                     |
       | LCH   | ichunutil           | 7.2.2           | iChun-Util-Mod-1.12.2 (1).jar           | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCH   | jei                 | 4.15.0.293      | jei_1.12.2-4.15.0.293.jar               | None                                     |
       | LCH   | mocreatures         | 12.0.5          | Mo-Creatures-Mod-1.12.2.jar             | None                                     |
       | LCH   | morph               | 7.1.3           | Morphing-Mod-1.12.2.jar                 | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCH   | nei                 | 2.4.1           | Not-Enough-Items-1.12.2-Recommended.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | savemystronghold    | 1.12.2-1.0.0    | savemystronghold-1.12.2-1.0.0.jar       | None                                     |
       | LCH   | sereneseasons       | 1.2.16          | Serene-Seasons-Mod-1.12.2.jar           | None                                     |
       | LCH   | storagedrawers      | 1.12.2-5.4.0    | Storage-Drawers-Mod-1.12.2.jar          | None                                     |
       | LCH   | tektopia            | 1.1.0           | TekTopia-Mod-1.12.2.jar                 | None                                     |
       | LCH   | vanillafix          | 1.0.10-SNAPSHOT | Vanilla-Fix-Mod-1.12.2.jar              | None                                     |
       | LCH   | worldedit           | 6.1.10-SNAPSHOT | WorldEdit-1.12.2.jar                    | None                                     |
       | LCH   | orelib              | 3.6.0.1         | OreLib-1.12.2-3.6.0.1.jar               | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCH   | dsurround           | 3.5.4.3         | Dynamic-Surroundings-Mod-1.12.2 (1).jar | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
  Loaded coremods (and transformers): SSLoadingPlugin (Serene-Seasons-Mod-1.12.2.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
                                        org.orecruncher.dsurround.asm.Transformer
                                      VanillaFixLoadingPlugin (Vanilla-Fix-Mod-1.12.2.jar)
  GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13587 Compatibility Profile Context 20.2.1 26.20.15019.1003' Renderer: 'Radeon RX550/550 Series'
  Suspected Mods: Better Portals (betterportals)
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
  LWJGL: 2.9.4
  OpenGL: Radeon RX550/550 Series GL version 4.6.13587 Compatibility Profile Context 20.2.1 26.20.15019.1003, ATI Technologies Inc.
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 4x AMD Ryzen 3 1300X Quad-Core Processor

**Comment by Johni0702** [comment]
Update Optifine.
