### ISSUE TITLE
Error Message/ Something Missing? It's not letting minecraft load in.

### ISSUE THREAD

**Issue by PurpleHattedSpider** [Johni0702/BetterPortals#477]
Basically, I just got the mod. I am trying to play it on 1.12.2 but whenever Minecraft finishes loading version 1.12.2 with forge it does not work and it says "You must include the right dependencies for Better Portals: Requires forgelin any (missing)". I have the latest.log right here:

[20:24:09] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:24:09] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:24:09] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[20:24:09] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2847 for Minecraft 1.12.2 loading
[20:24:09] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft Launcher\runtime\jre-x64
[20:24:09] [main/WARN] [FML]: The coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin) is not signed!
[20:24:09] [main/WARN] [FML]: The coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin) is not signed!
[20:24:09] [main/INFO] [FML]: Searching C:\Users\nicky\AppData\Roaming\.minecraft\mods for mods
[20:24:09] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from betterportals-0.3.7.7.jar
[20:24:09] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:24:09] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[20:24:09] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/nicky/AppData/Roaming/.minecraft/mods/betterportals-0.3.7.7.jar Service=LaunchWrapper Env=CLIENT
[20:24:10] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[20:24:10] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:24:10] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:24:10] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:24:14] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[20:24:14] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[20:24:14] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:24:14] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[20:24:15] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[20:24:15] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@4f20a5e0
[20:24:15] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[20:24:16] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[20:24:16] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[20:24:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[20:24:16] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[20:24:16] [main/ERROR] [mixin/betterportals]: Couldn't find kotlin.Pair class, Forgelin is probably missing, skipping all mixins!
[20:24:16] [main/ERROR] [mixin/betterportals]: Couldn't find kotlin.Pair class, Forgelin is probably missing, skipping all mixins!
[20:24:16] [main/ERROR] [mixin/betterportals]: Couldn't find kotlin.Pair class, Forgelin is probably missing, skipping all mixins!
[20:24:16] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[20:24:18] [Client thread/INFO] [net.minecraft.client.Minecraft]: Setting user: DisintegrateYT
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: lastServer:
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.pickItem:key.mouse.middle
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.playerlist:key.keyboard.tab
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.advancements:key.keyboard.l
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.hotbar.5:key.keyboard.5
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.hotbar.6:key.keyboard.6
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.hotbar.7:key.keyboard.7
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.hotbar.8:key.keyboard.8
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.hotbar.1:key.keyboard.1
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.hotbar.2:key.keyboard.2
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.hotbar.3:key.keyboard.3
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.hotbar.4:key.keyboard.4
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.sprint:key.keyboard.left.control
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.forward:key.keyboard.w
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.drop:key.keyboard.q
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.back:key.keyboard.s
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.attack:key.mouse.left
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.use:key.mouse.right
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.saveToolbarActivator:key.keyboard.c
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.smoothCamera:key.keyboard.unknown
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.right:key.keyboard.d
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.jump:key.keyboard.space
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.sneak:key.keyboard.left.shift
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.spectatorOutlines:key.keyboard.unknown
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.left:key.keyboard.a
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.command:key.keyboard.slash
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.screenshot:key.keyboard.f2
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.hotbar.9:key.keyboard.9
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.togglePerspective:key.keyboard.f5
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.chat:key.keyboard.t
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.inventory:key.keyboard.e
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.fullscreen:key.keyboard.f11
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.loadToolbarActivator:key.keyboard.x
[20:24:29] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.swapHands:key.keyboard.f
[20:24:29] [Client thread/INFO] [net.minecraft.client.Minecraft]: LWJGL Version: 2.9.4
[20:24:34] [Client thread/INFO] [FML]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 846823352 bytes (807 MB) / 1073741824 bytes (1024 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 24.20.100.6292' Renderer: 'Intel(R) UHD Graphics 600'
[20:24:34] [Client thread/INFO] [FML]: MinecraftForge v14.23.5.2847 Initialized
[20:24:34] [Client thread/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[20:24:34] [Client thread/INFO] [FML]: Invalid recipe found with multiple oredict ingredients in the same ingredient...
[20:24:34] [Client thread/INFO] [FML]: Replaced 1227 ore ingredients
[20:24:35] [Client thread/INFO] [FML]: Searching C:\Users\nicky\AppData\Roaming\.minecraft\mods for mods
[20:24:37] [Client thread/WARN] [FML]: Mod betterportals is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 0.3.7.7
[20:24:38] [Client thread/INFO] [FML]: Forge Mod Loader has identified 5 mods to load
[20:24:38] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod betterportals (Better Portals) requires [forgelin]
[20:24:38] [Client thread/ERROR] [FML]: An exception was thrown, the game will display an error screen and halt.
net.minecraftforge.fml.common.MissingModsException: Mod betterportals (Better Portals) requires [forgelin]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:266) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:572) ~[Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[20:24:38] [Client thread/WARN] [FML]: EventBus 0 shutting down - future events will not be posted.
[20:24:38] [Client thread/INFO] [net.minecraft.client.resources.SimpleReloadableResourceManager]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Better Portals
[20:24:39] [Client thread/WARN] [FML]: There were errors previously. Not beginning mod initialization phase
[20:24:41] [Thread-3/INFO] [FML]: Using sync timing. 200 frames of Display.update took 221212500 nanos
[20:24:42] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Starting up SoundSystem...
[20:24:42] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: Initializing LWJGL OpenAL
[20:24:42] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[20:24:44] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: OpenAL initialized.
[20:24:44] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Sound engine started
[20:24:46] [Client thread/INFO] [com.mojang.text2speech.NarratorWindows]: Narrator library for x64 successfully loaded

Please Help

And yes, the mod is in the folder.

**Comment by PurpleHattedSpider** [comment]
And yes, the mod is in the folder.

**Comment by Johni0702** [comment]
https://www.curseforge.com/minecraft/mc-mods/betterportals/relations/dependencies?filter-related-dependencies=3
