### ISSUE TITLE
my game crashes whenever i start a survival world

### ISSUE THREAD

**Issue by luck4sc** [Johni0702/BetterPortals#489]
this is the crash report 
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 3/18/20 11:32 AM
Description: Exception in server tick loop

java.lang.IllegalStateException: Mixin is NOT loaded. Install MixinBootstrap. https://www.curseforge.com/minecraft/mc-mods/immersive-portals-for-forge
	at com.qouteall.immersive_portals.ModMain.checkMixinState(ModMain.java:69) ~[?:0.15] {re:classloading}
	at com.qouteall.immersive_portals.ModMainForge.onServerTick(ModMainForge.java:94) ~[?:0.15] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_1_ModMainForge_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPreServerTick(BasicEventHooks.java:114) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:762) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:161) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Mac OS X (x86_64) version 10.15.3
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1392057592 bytes (1327 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/OptiFine_1.14.4_HD_U_F5.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.2.0.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.0
	FML Language Providers: 
		javafml@28.2
		minecraft@1
	Mod List: 
		forge-1.14.4-28.2.0-client.jar Minecraft {minecraft@1.14.4 DONE}
		immersive-portals-0.15(for+mc+1.14+with+forge).jar Immersive Portals {immersive_portals@0.15 DONE}
		forge-1.14.4-28.2.0-universal.jar Forge {forge@28.2.0 DONE}
		MinecraftCapes Forge 1.14.4.jar James090500's MinecraftCapes Mod {minecraftcapes@9.8 DONE}
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:forge, mod:immersive_portals, mod:minecraftcapes
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.14.4_HD_U_F5
	OptiFine Build: 20191204-141250
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 NVIDIA-14.0.31 355.11.11.10.10.143
	OpenGlRenderer: NVIDIA GeForce GT 755M OpenGL Engine
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Johni0702** [comment]
1. Wrong mod
2. Try reading the error message
