### ISSUE TITLE
Incompatibility with Dynamic Surroundings

### ISSUE THREAD

**Issue by Silivek** [Johni0702/BetterPortals#532]
I cannot run this mod with Dynamic Surroundings, it causes the game to crash on startup.
Here is the log:
`[21:33:53] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:33:54] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:33:54] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[21:33:54] [main/INFO]: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2 loading
[21:33:54] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\Liam\Twitch\Minecraft\Install\runtime\jre-x64
[21:33:54] [main/INFO]: Searching C:\Users\Liam\Twitch\Minecraft\Instances\Little Pack of Fun\mods for mods
[21:33:54] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from betterportals-0.3.7.7.jar
[21:33:54] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in colytra-1.12.2-1.2.0.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:33:54] [main/WARN]: The coremod c4.colytra.asm.ColytraLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:33:54] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in CreativeCore_v1.10.16_mc1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:33:54] [main/WARN]: The coremod com.creativemd.creativecore.core.CreativePatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:33:54] [main/WARN]: The coremod CreativePatchingLoader (com.creativemd.creativecore.core.CreativePatchingLoader) is not signed!
[21:33:54] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-1.0.2.31.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:33:54] [main/WARN]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:33:54] [main/WARN]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
[21:33:54] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from DynamicSurroundings-1.12.2-3.6.1.0.jar
[21:33:54] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:33:54] [main/WARN]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:33:54] [main/WARN]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[21:33:54] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in future-mc-1.12.2-0.2.3.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:33:54] [main/WARN]: The coremod FutureMC (thedarkcolour.futuremc.asm.CoreLoader) is not signed!
[21:33:54] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in InventoryTweaks-1.63.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:33:54] [main/WARN]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:33:54] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from malisiscore-1.12.2-6.5.1.jar
[21:33:54] [main/WARN]: The coremod ObfuscatePlugin (com.mrcrayfish.obfuscate.asm.ObfuscatePlugin) is not signed!
[21:33:54] [main/INFO]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_F5_MOD.jar
[21:33:54] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Quark-r1.6-179.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:33:54] [main/WARN]: The coremod Quark Plugin (vazkii.quark.base.asm.LoadingPlugin) is not signed!
[21:33:54] [main/WARN]: The coremod com.therandomlabs.randompatches.core.RPCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:33:54] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in SereneSeasons-1.12.2-1.2.18-universal.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:33:54] [main/WARN]: The coremod sereneseasons.asm.SSLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:33:54] [main/WARN]: The coremod SSLoadingPlugin (sereneseasons.asm.SSLoadingPlugin) is not signed!
[21:33:54] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in ToMeTinkersMC1.12.2-1.2.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:33:54] [main/WARN]: The coremod com.ToMe.ToMeTinkers.ToMeTinkersLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:33:54] [main/WARN]: The coremod ToMeTinkersLoadingPlugin (com.ToMe.ToMeTinkers.ToMeTinkersLoadingPlugin) is not signed!
[21:33:54] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:33:54] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.util.ServiceConfigurationError: org.spongepowered.asm.service.IMixinServiceBootstrap: Provider org.spongepowered.asm.service.modlauncher.MixinServiceModLauncherBootstrap could not be instantiated
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader$LazyIterator.access$700(ServiceLoader.java:323)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader$LazyIterator$2.run(ServiceLoader.java:407)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.security.AccessController.doPrivileged(Native Method)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:409)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.runBootServices(MixinService.java:77)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.<init>(MixinService.java:72)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.getInstance(MixinService.java:92)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.boot(MixinService.java:102)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:76)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:44)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.newInstance(Class.java:442)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.SecurityException: class "org.spongepowered.asm.service.ServiceInitialisationException"'s signer information does not match signer information of other classes in the same package
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.security.AccessController.doPrivileged(Native Method)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.getDeclaredConstructors0(Native Method)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.getConstructor0(Class.java:3075)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.newInstance(Class.java:412)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
[21:33:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 18 more
`
It seems the main issue is from differing versions of "spongepowered" between the two mods that causes it to crash even though I am not currently using a server or a sponge server.

**Comment by Johni0702** [comment]
SpongePowered's Mixin is a useful library used by many mods as well as Sponge.
BP currently includes an older version than DS. To work around the issue, make sure DS is loaded before BP by e.g. renaming BP's jar to start with "zzz" so it's alphabetically behind DS.
