### ISSUE TITLE
Need an uptade?

### ISSUE THREAD

**Issue by JOqupa** [Johni0702/BetterPortals#557]
Recently i updated the Twilight forest and the Aether Legacy. Then i came with this error wich is fix if a remove BetterPortals and other mod. Btw i use Twitch launcher.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  McLib core mod (mclib-2.0.3-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MMFMLCorePlugin (MultiMine-1.12.2.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 8/24/20 8:12 PM
Description: Initializing game

java.lang.NoClassDefFoundError: de/johni0702/minecraft/betterportals/impl/aether/common/blocks/BlockBetterAetherPortal
	at de.johni0702.minecraft.betterportals.impl.aether.common.ExtensionsKt$initAether$2.invoke(Extensions.kt:54)
	at de.johni0702.minecraft.betterportals.impl.aether.common.ExtensionsKt$initAether$2.invoke(Extensions.kt)
	at de.johni0702.minecraft.betterportals.impl.BetterPortalsMod.registerBlocks(BetterPortalsMod.kt:148)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_632_BetterPortalsMod_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: de.johni0702.minecraft.betterportals.impl.aether.common.blocks.BlockBetterAetherPortal
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more
Caused by: java.lang.NoClassDefFoundError: com/legacy/aether/blocks/portal/BlockAetherPortal
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 21 more
Caused by: java.lang.ClassNotFoundException: com.legacy.aether.blocks.portal.BlockAetherPortal
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 25 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at de.johni0702.minecraft.betterportals.impl.aether.common.ExtensionsKt$initAether$2.invoke(Extensions.kt:54)
	at de.johni0702.minecraft.betterportals.impl.aether.common.ExtensionsKt$initAether$2.invoke(Extensions.kt)
	at de.johni0702.minecraft.betterportals.impl.BetterPortalsMod.registerBlocks(BetterPortalsMod.kt:148)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_632_BetterPortalsMod_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by MrSteave** [comment]
I'm also experiencing the same issue. I added the Aether Legacy into my working modpack and it suddenly stopped launching and was giving this same error. Any ideas on what's causing this?

**Comment by Johni0702** [comment]
Try downgrading Aether Legacy. It's likely that an update of theirs changed something with their portal which then broke BP's integration since it has to relay on a significant amount of internals.
Or disable BP's Aether support in its config.

I've lost interest in this mod, so unless someone else picks it up (which seems unlikely given this is 1.12.2), this probably won't get fixed.

**Comment by JOqupa** [comment]
Is because the Aether legacy update. Another mod i had had the same problem but he actualize it and problem solve.

**Comment by Furglitch** [comment]
Just for anyone looking for a 'fix', Aether Legacy v1.4.4 is the last version that works with BetterPortals. Any higher and you get the crash on launch.
