### ISSUE TITLE
The game crashed whilst initializing game (Aether Mod)

### ISSUE THREAD

**Issue by pollyevamay** [Johni0702/BetterPortals#579]
After loading the mods minecraft crashes and shows
```
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: de/johni0702/minecraft/betterportals/impl/aether/common/blocks/BlockBetterAetherPortal
Exit Code: -1
```
in the launcher and this
```
// Who set us up the TNT?

Time: 11/24/20 7:00 PM
Description: Initializing game

java.lang.NoClassDefFoundError: de/johni0702/minecraft/betterportals/impl/aether/common/blocks/BlockBetterAetherPortal
	at de.johni0702.minecraft.betterportals.impl.aether.common.ExtensionsKt$initAether$2.invoke(Extensions.kt:54)
	at de.johni0702.minecraft.betterportals.impl.aether.common.ExtensionsKt$initAether$2.invoke(Extensions.kt)
	at de.johni0702.minecraft.betterportals.impl.BetterPortalsMod.registerBlocks(BetterPortalsMod.kt:148)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_847_BetterPortalsMod_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: de.johni0702.minecraft.betterportals.impl.aether.common.blocks.BlockBetterAetherPortal
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more
Caused by: java.lang.NoClassDefFoundError: com/legacy/aether/blocks/portal/BlockAetherPortal
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 21 more
Caused by: java.lang.ClassNotFoundException: com.legacy.aether.blocks.portal.BlockAetherPortal
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 25 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at de.johni0702.minecraft.betterportals.impl.aether.common.ExtensionsKt$initAether$2.invoke(Extensions.kt:54)
	at de.johni0702.minecraft.betterportals.impl.aether.common.ExtensionsKt$initAether$2.invoke(Extensions.kt)
	at de.johni0702.minecraft.betterportals.impl.BetterPortalsMod.registerBlocks(BetterPortalsMod.kt:148)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_847_BetterPortalsMod_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
in the logs.

Heres some additional things if it helps
```
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at de.johni0702.minecraft.betterportals.impl.aether.common.ExtensionsKt$initAether$2.invoke(Extensions.kt:54)
	at de.johni0702.minecraft.betterportals.impl.aether.common.ExtensionsKt$initAether$2.invoke(Extensions.kt)
	at de.johni0702.minecraft.betterportals.impl.BetterPortalsMod.registerBlocks(BetterPortalsMod.kt:148)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_847_BetterPortalsMod_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 349681696 bytes (333 MB) / 3388997632 bytes (3232 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 99 mods loaded, 99 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version                  | Source                                         | Signature                                |
	|:----- |:--------------------------------- |:------------------------ |:---------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                         | 1.12.2                   | minecraft.jar                                  | None                                     |
	| LCH   | mcp                               | 9.42                     | minecraft.jar                                  | None                                     |
	| LCH   | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2854.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                             | 14.23.5.2854             | forge-1.12.2-14.23.5.2854.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | micdoodlecore                     |                          | minecraft.jar                                  | None                                     |
	| LCH   | opencomputers|core                | 1.7.5.192                | minecraft.jar                                  | None                                     |
	| LCH   | actuallyadditions                 | 1.12.2-r152              | ActuallyAdditions-1.12.2-r152.jar              | None                                     |
	| LCH   | aether_legacy                     | 1.5.2                    | aether-1.12.2-v1.5.2.jar                       | None                                     |
	| LCH   | jei                               | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                      | None                                     |
	| LCH   | appleskin                         | 1.0.14                   | AppleSkin-mc1.12-1.0.14.jar                    | None                                     |
	| LCH   | ctm                               | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar                      | None                                     |
	| LCH   | appliedenergistics2               | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar           | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCH   | mantle                            | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                       | None                                     |
	| LCH   | chisel                            | MC1.12.2-1.0.2.45        | Chisel-MC1.12.2-1.0.2.45.jar                   | None                                     |
	| LCH   | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                         | None                                     |
	| LCH   | endercore                         | 1.12.2-0.5.76            | EnderCore-1.12.2-0.5.76.jar                    | None                                     |
	| LCH   | thaumcraft                        | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar               | None                                     |
	| LCH   | codechickenlib                    | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | redstoneflux                      | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar        | None                                     |
	| LCH   | cofhcore                          | 4.6.6                    | CoFHCore-1.12.2-4.6.6.1-universal.jar          | None                                     |
	| LCH   | cofhworld                         | 1.4.0                    | CoFHWorld-1.12.2-1.4.0.1-universal.jar         | None                                     |
	| LCH   | thermalfoundation                 | 2.6.7                    | ThermalFoundation-1.12.2-2.6.7.1-universal.jar | None                                     |
	| LCH   | thermalexpansion                  | 5.5.7                    | ThermalExpansion-1.12.2-5.5.7.1-universal.jar  | None                                     |
	| LCH   | enderio                           | 5.2.64                   | EnderIO-1.12.2-5.2.64.jar                      | None                                     |
	| LCH   | enderiointegrationtic             | 5.2.64                   | EnderIO-1.12.2-5.2.64.jar                      | None                                     |
	| LCH   | tconstruct                        | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar               | None                                     |
	| LCH   | galacticraftcore                  | 4.0.2.281                | GalacticraftCore-1.12.2-4.0.2.281.jar          | None                                     |
	| LCH   | galacticraftplanets               | 4.0.2.281                | Galacticraft-Planets-1.12.2-4.0.2.281.jar      | None                                     |
	| LCH   | asmodeuscore                      | 0.0.22                   | AsmodeusCore-1.12.2-0.0.22.jar                 | None                                     |
	| LCH   | crafttweaker                      | 4.1.20                   | CraftTweaker2-1.12-4.1.20.602.jar              | None                                     |
	| LCH   | base                              | 3.13.0                   | base-1.12.2-3.13.0.jar                         | None                                     |
	| LCH   | bdlib                             | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                   | None                                     |
	| LCH   | forgelin                          | 1.8.4                    | Forgelin-1.8.4.jar                             | None                                     |
	| LCH   | betterportals                     | 0.3.7.7                  | betterportals-0.3.7.7.jar                      | None                                     |
	| LCH   | buildcraftlib                     | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                   | None                                     |
	| LCH   | buildcraftcore                    | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                   | None                                     |
	| LCH   | buildcraftbuilders                | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                   | None                                     |
	| LCH   | buildcrafttransport               | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                   | None                                     |
	| LCH   | buildcraftsilicon                 | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                   | None                                     |
	| LCH   | buildcraftcompat                  | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                   | None                                     |
	| LCH   | buildcraftenergy                  | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                   | None                                     |
	| LCH   | buildcraftfactory                 | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                   | None                                     |
	| LCH   | buildcraftrobotics                | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                   | None                                     |
	| LCH   | ceramics                          | 1.12-1.3.7               | Ceramics-1.12-1.3.7.jar                        | None                                     |
	| LCH   | chameleon                         | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                       | None                                     |
	| LCH   | chunkpregenerator                 | 2.1                      | Chunk+Pregenerator+V1.12-2.4E.jar              | None                                     |
	| LCH   | contenttweaker                    | 1.12.2-4.9.1             | ContentTweaker-1.12.2-4.9.1.jar                | None                                     |
	| LCH   | conarm                            | 1.2.5.9                  | conarm-1.12.2-1.2.5.9.jar                      | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCH   | ctgui                             | 1.0.0                    | CraftTweaker2-1.12-4.1.20.602.jar              | None                                     |
	| LCH   | crafttweakerjei                   | 2.0.3                    | CraftTweaker2-1.12-4.1.20.602.jar              | None                                     |
	| LCH   | ptrmodellib                       | 1.0.4                    | PTRLib-1.0.4.jar                               | None                                     |
	| LCH   | props                             | 2.6.3                    | Decocraft-2.6.3_1.12.2.jar                     | None                                     |
	| LCH   | dimdoors                          | 1.12.2-3.1.2+UNOFFICIAL  | DimensionalDoors-1.12.2-3.1.2-UNOFFICIAL.jar   | None                                     |
	| LCH   | orelib                            | 3.6.0.1                  | OreLib-1.12.2-3.6.0.1.jar                      | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | dsurround                         | 3.6.2.1                  | DynamicSurroundings-1.12.2-3.6.2.1.jar         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | dynamictrees                      | 1.12.2-0.9.21            | DynamicTrees-1.12.2-0.9.21.jar                 | None                                     |
	| LCH   | dynmap                            | 3.1-beta5-431            | Dynmap-3.1-beta5-forge-1.12.2.jar              | None                                     |
	| LCH   | enderiobase                       | 5.2.64                   | EnderIO-1.12.2-5.2.64.jar                      | None                                     |
	| LCH   | enderioconduits                   | 5.2.64                   | EnderIO-1.12.2-5.2.64.jar                      | None                                     |
	| LCH   | enderioconduitsappliedenergistics | 5.2.64                   | EnderIO-1.12.2-5.2.64.jar                      | None                                     |
	| LCH   | opencomputers                     | 1.7.5.192                | OpenComputers-MC1.12.2-1.7.5.192.jar           | None                                     |
	| LCH   | enderioconduitsopencomputers      | 5.2.64                   | EnderIO-1.12.2-5.2.64.jar                      | None                                     |
	| LCH   | enderioconduitsrefinedstorage     | 5.2.64                   | EnderIO-1.12.2-5.2.64.jar                      | None                                     |
	| LCH   | enderiointegrationforestry        | 5.2.64                   | EnderIO-1.12.2-5.2.64.jar                      | None                                     |
	| LCH   | enderiointegrationticlate         | 5.2.64                   | EnderIO-1.12.2-5.2.64.jar                      | None                                     |
	| LCH   | enderioinvpanel                   | 5.2.64                   | EnderIO-1.12.2-5.2.64.jar                      | None                                     |
	| LCH   | enderiomachines                   | 5.2.64                   | EnderIO-1.12.2-5.2.64.jar                      | None                                     |
	| LCH   | enderiopowertools                 | 5.2.64                   | EnderIO-1.12.2-5.2.64.jar                      | None                                     |
	| LCH   | enderioendergy                    | 5.2.64                   | EnderIO-endergy-1.12.2-5.2.64.jar              | None                                     |
	| LCH   | silentlib                         | 3.0.13                   | SilentLib-1.12.2-3.0.14+168.jar                | None                                     |
	| LCH   | extendeddays                      | 0.2.9                    | ExtendedDays-1.12.2-0.2.9-28.jar               | None                                     |
	| LCH   | mjrlegendslib                     | 1.12.2-1.2.0             | MJRLegendsLib-1.12.2-1.2.0.jar                 | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCH   | zollerngalaxy                     | 2.0.20                   | ZollernGalaxy-1.12.2-v2.0.20.jar               | None                                     |
	| LCH   | extraplanets                      | 1.12.2-0.7.0             | ExtraPlanets-1.12.2-0.7.0.jar                  | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCH   | extrautils2                       | 1.0                      | extrautils2-1.12-1.9.9.jar                     | None                                     |
	| LCH   | farseek                           | 2.5.1                    | Farseek-1.12-2.5.1.jar                         | None                                     |
	| LCH   | cfm                               | 6.3.1                    | furniture-6.3.1-1.12.2.jar                     | None                                     |
	| LCH   | galaxyspace                       | 2.0.14                   | GalaxySpace-1.12.2-2.0.14.jar                  | None                                     |
	| LCH   | advgenerators                     | 0.9.20.12                | generators-0.9.20.12-mc1.12.2.jar              | None                                     |
	| LCH   | gravestone                        | 1.10.3                   | gravestone-1.10.3.jar                          | None                                     |
	| LCH   | waila                             | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                    | None                                     |
	| LCH   | ironchest                         | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                | None                                     |
	| LCH   | jeiintegration                    | 1.6.0                    | jeiintegration_1.12.2-1.6.0.jar                | None                                     |
	| LCH   | journeymap                        | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                    | None                                     |
	| LCH   | moreplanets                       | 2.0.24                   | More-Planets-1.12.2-2.0.24-GC251.jar           | b3468b224a74e296555ad7efeb35f482e6f445de |
	| LCH   | mousetweaks                       | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                  | None                                     |
	| LCH   | playtimelogger                    | 1.1                      | PlaytimeLogger+MC1.12.2+v1.1.jar               | None                                     |
	| LCH   | storagedrawers                    | 5.2.2                    | StorageDrawers-1.12.2-5.4.2.jar                | None                                     |
	| LCH   | streams                           | 0.4.9                    | Streams-1.12-0.4.9.jar                         | None                                     |
	| LCH   | thaumicwaila                      | 1.12.2-0.0.2             | ThaumicWaila-1.12.2-0.0.2.jar                  | None                                     |
	| LCH   | thermaldynamics                   | 2.5.6                    | ThermalDynamics-1.12.2-2.5.6.1-universal.jar   | None                                     |
	| LCH   | thermalinnovation                 | 0.3.6                    | ThermalInnovation-1.12.2-0.3.6.1-universal.jar | None                                     |
	| LCH   | tcomplement                       | 1.12.2-0.4.3             | TinkersComplement-1.12.2-0.4.3.jar             | None                                     |
	| LCH   | tinkersjei                        | 1.2                      | tinkersjei-1.2.jar                             | None                                     |
	| LCH   | tinkertoolleveling                | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar            | None                                     |
	| LCH   | toolbelt                          | 1.9.13                   | ToolBelt-1.12.2-1.9.13.jar                     | None                                     |
	| LCH   | unlimitedchiselworks              | 0.3.4                    | UnlimitedChiselWorks-0.3.4.jar                 | None                                     |
	| LCH   | wearablebackpacks                 | 3.1.4                    | WearableBackpacks-1.12.2-3.1.4.jar             | None                                     |
	| LCH   | gctweaks                          | 1.5.1                    | GalacticTweaks-1.5.1.jar                       | 20692d890dcfa0d9cf061915fc32d00d1f295cbc |

	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.281.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  li.cil.oc.common.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
TransformLoader (DynamicSurroundings-1.12.2-3.6.2.1.jar)
  
GSHooksLoader (GalaxySpace-1.12.2-2.0.14.jar)
  galaxyspace.core.hooklib.minecraft.PrimaryClassTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
FarseekCoreMod (Farseek-1.12-2.5.1.jar)
  farseek.core.FarseekClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 457.30' Renderer: 'GeForce GTX 1650/PCIe/SSE2'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Authlib is : /C:/Users/jacass66/AppData/Roaming/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
```

**Comment by pollyevamay** [comment]
Saw there were similar issues and the solution was to downgrade the aether mod

**Comment by NicholasBastion** [comment]
What version should I downgrade to?

**Comment by SirStig** [comment]
> What version should I downgrade to?

What worked for me was to downgrade to the aether legacy versions. 1.4.4 or lower
