### ISSUE TITLE
game crashes on startup

### ISSUE THREAD

**Issue by omar909** [Johni0702/BetterPortals#586]

**Comment by Shibva** [comment]
same issue

Dynamic Surroundings seems to be causing this as I have noted

the log

[19:43:11] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:43:11] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:43:11] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[19:43:11] [main/INFO]: Forge Mod Loader version 14.23.5.2855 for Minecraft 1.12.2 loading
[19:43:11] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at D:\Install\runtime\jre-x64
[19:43:11] [main/INFO]: Searching D:\Instances\EAS\mods for mods
[19:43:11] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from betterportals-0.3.7.7.jar
[19:43:11] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from DynamicSurroundings-1.12.2-3.6.1.0.jar
[19:43:11] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:43:11] [main/WARN]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:43:11] [main/WARN]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[19:43:11] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:43:11] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.util.ServiceConfigurationError: org.spongepowered.asm.service.IMixinServiceBootstrap: Provider org.spongepowered.asm.service.modlauncher.MixinServiceModLauncherBootstrap could not be instantiated
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader$LazyIterator.access$700(ServiceLoader.java:323)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader$LazyIterator$2.run(ServiceLoader.java:407)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.security.AccessController.doPrivileged(Native Method)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:409)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.runBootServices(MixinService.java:77)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.<init>(MixinService.java:72)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.getInstance(MixinService.java:92)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.boot(MixinService.java:102)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:76)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:44)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.newInstance(Class.java:442)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.SecurityException: class "org.spongepowered.asm.service.ServiceInitialisationException"'s signer information does not match signer information of other classes in the same package
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.security.AccessController.doPrivileged(Native Method)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.getDeclaredConstructors0(Native Method)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.getConstructor0(Class.java:3075)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.newInstance(Class.java:412)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
[19:43:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 18 more

from what A friend told me its a mixin issue

but theres a mod that exists that fixes this 

heres the mod
https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility
