### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by BraveCaperCat** [Johni0702/BetterPortals#612]
Crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
ForgelinPlugin (Forgelin-1.8.4.jar)
SecurityCraftLoadingPlugin ([1.12.2] SecurityCraft v1.9.0.2.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 3/3/22 10:37 AM
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/EntityRenderer
at net.minecraftforge.client.ForgeHooksClient.shouldUseVanillaReloadableListener(ForgeHooksClient.java:959)
at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:808)
at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.EntityRenderer
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
-- Head --
Thread: Client thread
Stacktrace:
at net.minecraftforge.client.ForgeHooksClient.shouldUseVanillaReloadableListener(ForgeHooksClient.java:959)
at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:808)
at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
Minecraft Version: 1.12.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 1173713264 bytes (1119 MB) / 1585446912 bytes (1512 MB) up to 3817865216 bytes (3641 MB)
JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP 9.42 Powered by Forge 14.23.5.2859 39 mods loaded, 39 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

| State | ID                   | Version          | Source                                      | Signature                                |
|:----- |:-------------------- |:---------------- |:------------------------------------------- |:---------------------------------------- |
| LC    | minecraft            | 1.12.2           | minecraft.jar                               | None                                     |
| LC    | mcp                  | 9.42             | minecraft.jar                               | None                                     |
| LC    | FML                  | 8.0.99.99        | forge-1.12.2-14.23.5.2859.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| LC    | forge                | 14.23.5.2859     | forge-1.12.2-14.23.5.2859.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| LC    | randompatches        | 1.12.2-1.22.1.10 | randompatches-1.12.2-1.22.1.10.jar          | None                                     |
| LC    | securitycraft        | v1.9.0.2         | [1.12.2] SecurityCraft v1.9.0.2.jar         | None                                     |
| LC    | baubles              | 1.5.2            | Baubles-1.12-1.5.2.jar                      | None                                     |
| LC    | forgelin             | 1.8.4            | Forgelin-1.8.4.jar                          | None                                     |
| L     | betterportals        | 0.3.7.7          | betterportals-0.3.7.7.jar                   | None                                     |
| L     | craftstudioapi       | 1.0.0            | CraftStudio-1.0.0.93-mc1.12-alpha.jar       | None                                     |
| L     | dronecraft           | 0.0.1            | Dronecraft_0.35.jar                         | None                                     |
| L     | drones               | 0.3.1            | Drones-0.3.1.jar                            | None                                     |
| L     | refinedstorage       | 1.6.16           | refinedstorage-1.6.16.jar                   | None                                     |
| L     | exposer              | 1.2              | exposer-1.2.jar                             | None                                     |
| L     | jei                  | 4.16.1.301       | jei_1.12.2-4.16.1.301.jar                   | None                                     |
| L     | journeymap           | 1.12.2-5.7.1     | journeymap-1.12.2-5.7.1.jar                 | None                                     |
| L     | naturescompass       | 1.8.5            | NaturesCompass-1.12.2-1.8.5.jar             | None                                     |
| L     | nevokacore           | 1.0.2            | nevoka-core-1.0.2.jar                       | None                                     |
| L     | thaumcraft           | 6.1.BETA26       | Thaumcraft-1.12.2-6.1.BETA26.jar            | None                                     |
| L     | omlib                | 3.1.5-256        | omlib-1.12.2-3.1.5-256.jar                  | None                                     |
| L     | openmodularturrets   | 3.1.14-382       | openmodularturrets-1.12.2-3.1.14-382.jar    | None                                     |
| L     | randomportals        | 1.12.2-1.8.2.4   | randomportals-1.12.2-1.8.2.4.jar            | None                                     |
| L     | reborncore           | 3.19.5           | RebornCore-1.12.2-3.19.5-universal.jar      | None                                     |
| L     | rebornstorage        | 1.0.0            | RebornStorage-1.12.2-3.3.4.1.jar            | None                                     |
| L     | refinedstorageaddons | 0.4.5            | refinedstorageaddons-0.4.5.jar              | None                                     |
| L     | rsinfinitewireless   | 1.2              | rsinfinitewireless-1.2.jar                  | None                                     |
| L     | rslargepatterns      | 1.12.2-1.0.0.0   | RSLargePatterns-1.12.2-1.0.0.1.jar          | None                                     |
| L     | sdrones              | 1.3.1            | sdrones-1.3.1.jar                           | None                                     |
| L     | storagetech          | 6.0              | StorageTech R6.0.jar                        | None                                     |
| L     | tekdrone             | 1.0.0            | tekdrone-1.0.jar                            | None                                     |
| L     | tektopia             | 1.1.0            | tektopia-1.1.0.jar                          | None                                     |
| L     | tektopiainformation  | 1.11.0           | TektopiaInformation-1.12.2-1.1.0-1.11.0.jar | None                                     |
| L     | tektopiarecycler     | 1.3.0            | TektopiaRecycler-1.12.2-1.1.0-1.3.0.jar     | None                                     |
| L     | tektopiathief        | 1.3.0            | TektopiaThief-1.12.2-1.1.0-1.3.0.jar        | None                                     |
| L     | tektopiatinker       | 1.4.0            | TektopiaTinker-1.12.2-1.1.0-1.4.0.jar       | None                                     |
| L     | tektopiatrader       | 1.4.0            | TektopiaTrader-1.12.2-1.1.0-1.4.0.jar       | None                                     |
| L     | thaumicgrid          | 1.0.12           | ThaumicGrid-1.0.12.jar                      | None                                     |
| L     | thaumicjei           | 1.6.0            | ThaumicJEI-1.12.2-1.6.0-27.jar              | None                                     |
| L     | morerefinedstorage   | 1.1.10           | morerefinedstorage-1.2.01.jar               | None                                     |

Loaded coremods (and transformers): 
RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
com.therandomlabs.randompatches.core.RPTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)

SecurityCraftLoadingPlugin ([1.12.2] SecurityCraft v1.9.0.2.jar)

GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 461.79' Renderer: 'GeForce RTX 3060 Laptop GPU/PCIe/SSE2'
Launched Version: forge-14.23.5.2859
LWJGL: 2.9.4
OpenGL: GeForce RTX 3060 Laptop GPU/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.79, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: ~~ERROR~~ NullPointerException: null
Profiler Position: N/A (disabled)
CPU: 12x Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
Exit code: -1

**Comment by BraveCaperCat** [comment]
Does not crash after removing both mods
