### ISSUE TITLE
conflict with Dimensional Pockets II

### ISSUE THREAD

**Issue by festro** [Johni0702/BetterPortals#616]
when visiting the pocket Dimension the view gets weird like I'm perpetual falling, all my equipment is gone, but when I get quit to menu and log back in everything is fine, I'm in the pocket dimension, all my gear is there, but when I leave same thing happens again;
I get this reference to your mod in the log(I noticed projectE and it's addons referenced too, but even removing them it still errors)
[19:16:57] [Server thread/WARN]: Failed to determine view of task: 
java.lang.Exception: null
	at de.johni0702.minecraft.view.impl.client.ViewDemuxingTaskQueue.wrapTask(ViewDemuxingTaskQueue.kt:46) [ViewDemuxingTaskQueue.class:?]
	at de.johni0702.minecraft.view.impl.client.ViewDemuxingTaskQueue.offer(ViewDemuxingTaskQueue.kt:86) [ViewDemuxingTaskQueue.class:?]
	at de.johni0702.minecraft.view.impl.client.ViewDemuxingTaskQueue.offer(ViewDemuxingTaskQueue.kt:16) [ViewDemuxingTaskQueue.class:?]
	at java.util.AbstractQueue.add(AbstractQueue.java:95) [?:1.8.0_51]
	at net.minecraft.client.Minecraft.func_152343_a(Minecraft.java:3159) [bib.class:?]
	at net.minecraft.client.Minecraft.func_152344_a(Minecraft.java:3168) [bib.class:?]
	at moze_intel.projecte.integration.jei.PEJeiPlugin.refresh(PEJeiPlugin.java:69) [PEJeiPlugin.class:?]
	at moze_intel.projecte.PECore.refreshJEI(PECore.java:215) [PECore.class:?]
	at moze_intel.projecte.emc.EMCMapper.map(EMCMapper.java:151) [EMCMapper.class:?]
	at moze_intel.projecte.PECore.serverStarting(PECore.java:175) [PECore.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:797) [Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:297) [FMLCommonHandler.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.optifine.reflect.Reflector.callBoolean(Reflector.java:857) [Reflector.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:241) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

**Comment by Johni0702** [comment]
Probably the same issue as #581 except the offending method is [here](https://github.com/TheCosmicNebula/DimensionalPocketsII/blob/cc460894639f1e36f2eeb7e79aac44c8853ed58f/src/main/java/com/zeher/dimpockets/pocket/core/shift/ShifterUtil.java#L31). Idk why people keep copying the same broken code from each other...

The stacktrace seems unrelated, and as you said yourself can't even happen if you remove PE (a similar one may happen but the one you sent is literally impossible without PE).

**Comment by festro** [comment]
Ok thanks for looking into it, I opened an issue there too as that mods was also listed in vanilla fix as potential causes.
