### ISSUE TITLE
[1.12.2] Startup Crash with Securitycraft

### ISSUE THREAD

**Issue by Cryberry** [Johni0702/BetterPortals#620]
I was putting a modpack together and identified the SecurityCraft mod as the cause of a crash on startup.

Here's the crash log from the whole modpack during my testing, the second is with just the most recent versions of BetterPortals, Forgelin, and SecurityCraft. This should be reproducible by putting those three mods in the same installation.

[crash-2022-06-11_18.42.25-client.txt](https://github.com/Johni0702/BetterPortals/files/8884901/crash-2022-06-11_18.42.25-client.txt)
[crash-2022-06-11_18.58.21-client.txt](https://github.com/Johni0702/BetterPortals/files/8884911/crash-2022-06-11_18.58.21-client.txt)

**Comment by Johni0702** [comment]
Duplicate of #547

**Comment by copygirl** [comment]
Just wanted to ask if this is resolvable?

If I change BetterPortals' .jar name to cause it to load first, SecurityCraft will fail to apply its mixins:
```
[11:13:12] [main/WARN] [mixin]: Mixin config securitycraft.mixins.json requires mixin subsystem version 0.8 but 0.7.11 was found. The mixin config will not be applied.
[11:13:12] [main/ERROR] [mixin]: Catching
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_412]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_412]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_412]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_412]
	[...]
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Required mixin config securitycraft.mixins.json requires mixin subsystem version 0.8
	at org.spongepowered.asm.mixin.transformer.MixinConfig.checkVersion(MixinConfig.java:417) ~[!betterportals-0.3.7.7.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:331) ~[!betterportals-0.3.7.7.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:894) ~[!betterportals-0.3.7.7.jar:?]
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:116) ~[!betterportals-0.3.7.7.jar:?]
	[...]
```
The mod is able to load but I think some of its features aren't working as expected. (Like cameras.)
